//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Utility.DBAccessor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    
    /// <summary>
    /// DtAlarmSmartPremonitorクラス
    /// </summary>
    [ModelMetadataType(typeof(DtAlarmSmartPremonitorModelMetaData))]
    public partial class DtAlarmSmartPremonitor
    {
        /// <summary>
        /// コンストラクタ
        /// </summary>
        public DtAlarmSmartPremonitor()
        {
        }
    
        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <param name="model">Rms.Server.Utility.Utility.Models.DtAlarmSmartPremonitorのインスタンス</param>
        public DtAlarmSmartPremonitor(Rms.Server.Utility.Utility.Models.DtAlarmSmartPremonitor model)
        {
            this.Sid = model.Sid;
            this.SmartId = model.SmartId;
            this.ChangeCountThreshold = model.ChangeCountThreshold;
            this.AnalysisResultErrorCode = model.AnalysisResultErrorCode;
            this.AlarmLevel = model.AlarmLevel;
            this.AlarmTitle = model.AlarmTitle;
            this.AlarmDescription = model.AlarmDescription;
            this.CreateDatetime = model.CreateDatetime;
            this.UpdateDatetime = model.UpdateDatetime;
        }
    
        /// <summary>
        /// このインスタンスの各プロパティに、引数に指定されたDtAlarmSmartPremonitorのプロパティの値をコピーする
        /// </summary>
        /// <param name="entity">コピー元のDtAlarmSmartPremonitor</param>
        public void CopyFrom(DtAlarmSmartPremonitor entity)
        {
            this.Sid = entity.Sid;
            this.SmartId = entity.SmartId;
            this.ChangeCountThreshold = entity.ChangeCountThreshold;
            this.AnalysisResultErrorCode = entity.AnalysisResultErrorCode;
            this.AlarmLevel = entity.AlarmLevel;
            this.AlarmTitle = entity.AlarmTitle;
            this.AlarmDescription = entity.AlarmDescription;
            this.CreateDatetime = entity.CreateDatetime;
            this.UpdateDatetime = entity.UpdateDatetime;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なRms.Server.Utility.Utility.Models.DtAlarmSmartPremonitor型に変換する。
        /// </summary>
        /// <returns></returns>
        public Rms.Server.Utility.Utility.Models.DtAlarmSmartPremonitor ToModel()
        {
            Rms.Server.Utility.Utility.Models.DtAlarmSmartPremonitor model = new Rms.Server.Utility.Utility.Models.DtAlarmSmartPremonitor();
            model.Sid = this.Sid;
            model.SmartId = this.SmartId;
            model.ChangeCountThreshold = this.ChangeCountThreshold;
            model.AnalysisResultErrorCode = this.AnalysisResultErrorCode;
            model.AlarmLevel = this.AlarmLevel;
            model.AlarmTitle = this.AlarmTitle;
            model.AlarmDescription = this.AlarmDescription;
            model.CreateDatetime = this.CreateDatetime;
            model.UpdateDatetime = this.UpdateDatetime;
    
            return model;
        }
    }
    
    /// <summary>
    /// DtAlarmSmartPremonitorのメタデータクラス
    /// </summary>
    public  class DtAlarmSmartPremonitorModelMetaData
    {
        [Key]
        [Required(ErrorMessage = "Sid is required.")]
        public long Sid { get; set; }
    
        [Required(ErrorMessage = "SmartId is required.")]
        [StringLength(2, ErrorMessage = "SmartId length should be less than 2 symbols.")]
        public string SmartId { get; set; }
    
        [Required(ErrorMessage = "ChangeCountThreshold is required.")]
        [StringLength(20, ErrorMessage = "ChangeCountThreshold length should be less than 20 symbols.")]
        public string ChangeCountThreshold { get; set; }
    
        [Required(ErrorMessage = "AnalysisResultErrorCode is required.")]
        [StringLength(20, ErrorMessage = "AnalysisResultErrorCode length should be less than 20 symbols.")]
        public string AnalysisResultErrorCode { get; set; }
    
        [Required(ErrorMessage = "AlarmLevel is required.")]
        public byte AlarmLevel { get; set; }
    
        [StringLength(200, ErrorMessage = "AlarmTitle length should be less than 200 symbols.")]
        public string AlarmTitle { get; set; }
    
        [StringLength(1024, ErrorMessage = "AlarmDescription length should be less than 1024 symbols.")]
        public string AlarmDescription { get; set; }
    
        [Required(ErrorMessage = "CreateDatetime is required.")]
        public System.DateTime CreateDatetime { get; set; }
    
        [Required(ErrorMessage = "UpdateDatetime is required.")]
        public System.DateTime UpdateDatetime { get; set; }
    
    }
}
