//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Utility.DBAccessor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    
    /// <summary>
    /// DtAlarmDefDirectoryUsageMonitorクラス
    /// </summary>
    [ModelMetadataType(typeof(DtAlarmDefDirectoryUsageMonitorModelMetaData))]
    public partial class DtAlarmDefDirectoryUsageMonitor
    {
        /// <summary>
        /// コンストラクタ
        /// </summary>
        public DtAlarmDefDirectoryUsageMonitor()
        {
        }
    
        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <param name="model">Rms.Server.Utility.Utility.Models.DtAlarmDefDirectoryUsageMonitorのインスタンス</param>
        public DtAlarmDefDirectoryUsageMonitor(Rms.Server.Utility.Utility.Models.DtAlarmDefDirectoryUsageMonitor model)
        {
            this.Sid = model.Sid;
            this.TypeCode = model.TypeCode;
            this.DirectoryPath = model.DirectoryPath;
            this.Size = model.Size;
            this.AnalysisResultErrorCode = model.AnalysisResultErrorCode;
            this.AlarmLevel = model.AlarmLevel;
            this.AlarmTitle = model.AlarmTitle;
            this.AlarmDescription = model.AlarmDescription;
            this.CreateDatetime = model.CreateDatetime;
            this.UpdateDatetime = model.UpdateDatetime;
        }
    
        /// <summary>
        /// このインスタンスの各プロパティに、引数に指定されたDtAlarmDefDirectoryUsageMonitorのプロパティの値をコピーする
        /// </summary>
        /// <param name="entity">コピー元のDtAlarmDefDirectoryUsageMonitor</param>
        public void CopyFrom(DtAlarmDefDirectoryUsageMonitor entity)
        {
            this.Sid = entity.Sid;
            this.TypeCode = entity.TypeCode;
            this.DirectoryPath = entity.DirectoryPath;
            this.Size = entity.Size;
            this.AnalysisResultErrorCode = entity.AnalysisResultErrorCode;
            this.AlarmLevel = entity.AlarmLevel;
            this.AlarmTitle = entity.AlarmTitle;
            this.AlarmDescription = entity.AlarmDescription;
            this.CreateDatetime = entity.CreateDatetime;
            this.UpdateDatetime = entity.UpdateDatetime;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なRms.Server.Utility.Utility.Models.DtAlarmDefDirectoryUsageMonitor型に変換する。
        /// </summary>
        /// <returns></returns>
        public Rms.Server.Utility.Utility.Models.DtAlarmDefDirectoryUsageMonitor ToModel()
        {
            Rms.Server.Utility.Utility.Models.DtAlarmDefDirectoryUsageMonitor model = new Rms.Server.Utility.Utility.Models.DtAlarmDefDirectoryUsageMonitor();
            model.Sid = this.Sid;
            model.TypeCode = this.TypeCode;
            model.DirectoryPath = this.DirectoryPath;
            model.Size = this.Size;
            model.AnalysisResultErrorCode = this.AnalysisResultErrorCode;
            model.AlarmLevel = this.AlarmLevel;
            model.AlarmTitle = this.AlarmTitle;
            model.AlarmDescription = this.AlarmDescription;
            model.CreateDatetime = this.CreateDatetime;
            model.UpdateDatetime = this.UpdateDatetime;
    
            return model;
        }
    }
    
    /// <summary>
    /// DtAlarmDefDirectoryUsageMonitorのメタデータクラス
    /// </summary>
    public  class DtAlarmDefDirectoryUsageMonitorModelMetaData
    {
        [Key]
        [Required(ErrorMessage = "Sid is required.")]
        public long Sid { get; set; }
    
        [Required(ErrorMessage = "TypeCode is required.")]
        [StringLength(30, ErrorMessage = "TypeCode length should be less than 30 symbols.")]
        public string TypeCode { get; set; }
    
        [Required(ErrorMessage = "DirectoryPath is required.")]
        [StringLength(300, ErrorMessage = "DirectoryPath length should be less than 300 symbols.")]
        public string DirectoryPath { get; set; }
    
        [Required(ErrorMessage = "Size is required.")]
        public int Size { get; set; }
    
        [Required(ErrorMessage = "AnalysisResultErrorCode is required.")]
        [StringLength(20, ErrorMessage = "AnalysisResultErrorCode length should be less than 20 symbols.")]
        public string AnalysisResultErrorCode { get; set; }
    
        [Required(ErrorMessage = "AlarmLevel is required.")]
        public byte AlarmLevel { get; set; }
    
        [StringLength(200, ErrorMessage = "AlarmTitle length should be less than 200 symbols.")]
        public string AlarmTitle { get; set; }
    
        [StringLength(1024, ErrorMessage = "AlarmDescription length should be less than 1024 symbols.")]
        public string AlarmDescription { get; set; }
    
        [Required(ErrorMessage = "CreateDatetime is required.")]
        public System.DateTime CreateDatetime { get; set; }
    
        [Required(ErrorMessage = "UpdateDatetime is required.")]
        public System.DateTime UpdateDatetime { get; set; }
    
    }
}
