//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Utility.DBAccessor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    
    /// <summary>
    /// DtAlarmDefConnectionMonitorクラス
    /// </summary>
    [ModelMetadataType(typeof(DtAlarmDefConnectionMonitorModelMetaData))]
    public partial class DtAlarmDefConnectionMonitor
    {
        /// <summary>
        /// コンストラクタ
        /// </summary>
        public DtAlarmDefConnectionMonitor()
        {
        }
    
        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <param name="model">Rms.Server.Utility.Utility.Models.DtAlarmDefConnectionMonitorのインスタンス</param>
        public DtAlarmDefConnectionMonitor(Rms.Server.Utility.Utility.Models.DtAlarmDefConnectionMonitor model)
        {
            this.Sid = model.Sid;
            this.TypeCode = model.TypeCode;
            this.ErrorCode = model.ErrorCode;
            this.AnalysisResultErrorCode = model.AnalysisResultErrorCode;
            this.Target = model.Target;
            this.ValueFrom = model.ValueFrom;
            this.ValueEqualFrom = model.ValueEqualFrom;
            this.ValueTo = model.ValueTo;
            this.ValueEqualTo = model.ValueEqualTo;
            this.AlarmLevel = model.AlarmLevel;
            this.AlarmTitle = model.AlarmTitle;
            this.AlarmDescription = model.AlarmDescription;
            this.CreateDatetime = model.CreateDatetime;
            this.UpdateDatetime = model.UpdateDatetime;
        }
    
        /// <summary>
        /// このインスタンスの各プロパティに、引数に指定されたDtAlarmDefConnectionMonitorのプロパティの値をコピーする
        /// </summary>
        /// <param name="entity">コピー元のDtAlarmDefConnectionMonitor</param>
        public void CopyFrom(DtAlarmDefConnectionMonitor entity)
        {
            this.Sid = entity.Sid;
            this.TypeCode = entity.TypeCode;
            this.ErrorCode = entity.ErrorCode;
            this.AnalysisResultErrorCode = entity.AnalysisResultErrorCode;
            this.Target = entity.Target;
            this.ValueFrom = entity.ValueFrom;
            this.ValueEqualFrom = entity.ValueEqualFrom;
            this.ValueTo = entity.ValueTo;
            this.ValueEqualTo = entity.ValueEqualTo;
            this.AlarmLevel = entity.AlarmLevel;
            this.AlarmTitle = entity.AlarmTitle;
            this.AlarmDescription = entity.AlarmDescription;
            this.CreateDatetime = entity.CreateDatetime;
            this.UpdateDatetime = entity.UpdateDatetime;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なRms.Server.Utility.Utility.Models.DtAlarmDefConnectionMonitor型に変換する。
        /// </summary>
        /// <returns></returns>
        public Rms.Server.Utility.Utility.Models.DtAlarmDefConnectionMonitor ToModel()
        {
            Rms.Server.Utility.Utility.Models.DtAlarmDefConnectionMonitor model = new Rms.Server.Utility.Utility.Models.DtAlarmDefConnectionMonitor();
            model.Sid = this.Sid;
            model.TypeCode = this.TypeCode;
            model.ErrorCode = this.ErrorCode;
            model.AnalysisResultErrorCode = this.AnalysisResultErrorCode;
            model.Target = this.Target;
            model.ValueFrom = this.ValueFrom;
            model.ValueEqualFrom = this.ValueEqualFrom;
            model.ValueTo = this.ValueTo;
            model.ValueEqualTo = this.ValueEqualTo;
            model.AlarmLevel = this.AlarmLevel;
            model.AlarmTitle = this.AlarmTitle;
            model.AlarmDescription = this.AlarmDescription;
            model.CreateDatetime = this.CreateDatetime;
            model.UpdateDatetime = this.UpdateDatetime;
    
            return model;
        }
    }
    
    /// <summary>
    /// DtAlarmDefConnectionMonitorのメタデータクラス
    /// </summary>
    public  class DtAlarmDefConnectionMonitorModelMetaData
    {
        [Key]
        [Required(ErrorMessage = "Sid is required.")]
        public long Sid { get; set; }
    
        [Required(ErrorMessage = "TypeCode is required.")]
        [StringLength(200, ErrorMessage = "TypeCode length should be less than 200 symbols.")]
        public string TypeCode { get; set; }
    
        [Required(ErrorMessage = "ErrorCode is required.")]
        [StringLength(20, ErrorMessage = "ErrorCode length should be less than 20 symbols.")]
        public string ErrorCode { get; set; }
    
        [Required(ErrorMessage = "AnalysisResultErrorCode is required.")]
        [StringLength(20, ErrorMessage = "AnalysisResultErrorCode length should be less than 20 symbols.")]
        public string AnalysisResultErrorCode { get; set; }
    
        [Required(ErrorMessage = "Target is required.")]
        [StringLength(30, ErrorMessage = "Target length should be less than 30 symbols.")]
        public string Target { get; set; }
    
        [Required(ErrorMessage = "ValueFrom is required.")]
        public int ValueFrom { get; set; }
    
        [Required(ErrorMessage = "ValueEqualFrom is required.")]
        public bool ValueEqualFrom { get; set; }
    
        [Required(ErrorMessage = "AlarmLevel is required.")]
        public byte AlarmLevel { get; set; }
    
        [StringLength(200, ErrorMessage = "AlarmTitle length should be less than 200 symbols.")]
        public string AlarmTitle { get; set; }
    
        [StringLength(1024, ErrorMessage = "AlarmDescription length should be less than 1024 symbols.")]
        public string AlarmDescription { get; set; }
    
        [Required(ErrorMessage = "CreateDatetime is required.")]
        public System.DateTime CreateDatetime { get; set; }
    
        [Required(ErrorMessage = "UpdateDatetime is required.")]
        public System.DateTime UpdateDatetime { get; set; }
    
    }
}
