//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Utility.DBAccessor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    
    /// <summary>
    /// DtAlarmDefTubeDeteriorationPremonitorクラス
    /// </summary>
    [ModelMetadataType(typeof(DtAlarmDefTubeDeteriorationPremonitorModelMetaData))]
    public partial class DtAlarmDefTubeDeteriorationPremonitor
    {
        /// <summary>
        /// コンストラクタ
        /// </summary>
        public DtAlarmDefTubeDeteriorationPremonitor()
        {
        }
    
        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <param name="model">Rms.Server.Utility.Utility.Models.DtAlarmDefTubeDeteriorationPremonitorのインスタンス</param>
        public DtAlarmDefTubeDeteriorationPremonitor(Rms.Server.Utility.Utility.Models.DtAlarmDefTubeDeteriorationPremonitor model)
        {
            this.Sid = model.Sid;
            this.TypeCode = model.TypeCode;
            this.ErrorCode = model.ErrorCode;
            this.AlarmLevel = model.AlarmLevel;
            this.AlarmTitle = model.AlarmTitle;
            this.AlarmDescription = model.AlarmDescription;
            this.CreateDatetime = model.CreateDatetime;
            this.UpdateDatetime = model.UpdateDatetime;
        }
    
        /// <summary>
        /// このインスタンスの各プロパティに、引数に指定されたDtAlarmDefTubeDeteriorationPremonitorのプロパティの値をコピーする
        /// </summary>
        /// <param name="entity">コピー元のDtAlarmDefTubeDeteriorationPremonitor</param>
        public void CopyFrom(DtAlarmDefTubeDeteriorationPremonitor entity)
        {
            this.Sid = entity.Sid;
            this.TypeCode = entity.TypeCode;
            this.ErrorCode = entity.ErrorCode;
            this.AlarmLevel = entity.AlarmLevel;
            this.AlarmTitle = entity.AlarmTitle;
            this.AlarmDescription = entity.AlarmDescription;
            this.CreateDatetime = entity.CreateDatetime;
            this.UpdateDatetime = entity.UpdateDatetime;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なRms.Server.Utility.Utility.Models.DtAlarmDefTubeDeteriorationPremonitor型に変換する。
        /// </summary>
        /// <returns></returns>
        public Rms.Server.Utility.Utility.Models.DtAlarmDefTubeDeteriorationPremonitor ToModel()
        {
            Rms.Server.Utility.Utility.Models.DtAlarmDefTubeDeteriorationPremonitor model = new Rms.Server.Utility.Utility.Models.DtAlarmDefTubeDeteriorationPremonitor();
            model.Sid = this.Sid;
            model.TypeCode = this.TypeCode;
            model.ErrorCode = this.ErrorCode;
            model.AlarmLevel = this.AlarmLevel;
            model.AlarmTitle = this.AlarmTitle;
            model.AlarmDescription = this.AlarmDescription;
            model.CreateDatetime = this.CreateDatetime;
            model.UpdateDatetime = this.UpdateDatetime;
    
            return model;
        }
    }
    
    /// <summary>
    /// DtAlarmDefTubeDeteriorationPremonitorのメタデータクラス
    /// </summary>
    public  class DtAlarmDefTubeDeteriorationPremonitorModelMetaData
    {
        [Key]
        [Required(ErrorMessage = "Sid is required.")]
        public long Sid { get; set; }
    
        [Required(ErrorMessage = "TypeCode is required.")]
        [StringLength(30, ErrorMessage = "TypeCode length should be less than 30 symbols.")]
        public string TypeCode { get; set; }
    
        [Required(ErrorMessage = "ErrorCode is required.")]
        [StringLength(20, ErrorMessage = "ErrorCode length should be less than 20 symbols.")]
        public string ErrorCode { get; set; }
    
        [Required(ErrorMessage = "AlarmLevel is required.")]
        public byte AlarmLevel { get; set; }
    
        [StringLength(200, ErrorMessage = "AlarmTitle length should be less than 200 symbols.")]
        public string AlarmTitle { get; set; }
    
        [StringLength(1024, ErrorMessage = "AlarmDescription length should be less than 1024 symbols.")]
        public string AlarmDescription { get; set; }
    
        [Required(ErrorMessage = "CreateDatetime is required.")]
        public System.DateTime CreateDatetime { get; set; }
    
        [Required(ErrorMessage = "UpdateDatetime is required.")]
        public System.DateTime UpdateDatetime { get; set; }
    
    }
}
