//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Utility.DBAccessor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    
    /// <summary>
    /// DtSmartAnalysisResultクラス
    /// </summary>
    [ModelMetadataType(typeof(DtSmartAnalysisResultModelMetaData))]
    public partial class DtSmartAnalysisResult
    {
        /// <summary>
        /// コンストラクタ
        /// </summary>
        public DtSmartAnalysisResult()
        {
        }
    
        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <param name="model">Rms.Server.Utility.Utility.Models.DtSmartAnalysisResultのインスタンス</param>
        public DtSmartAnalysisResult(Rms.Server.Utility.Utility.Models.DtSmartAnalysisResult model)
        {
            this.Sid = model.Sid;
            this.EquipmentUid = model.EquipmentUid;
            this.DiskSerialNumber = model.DiskSerialNumber;
            this.C5RawData = model.C5RawData;
            this.C5RawDataChanges = model.C5RawDataChanges;
            this.C5ChangesThreshhold = model.C5ChangesThreshhold;
            this.C5ChangesThreshholdOverCount = model.C5ChangesThreshholdOverCount;
            this.C5ChangesThreshholdLastDatetime = model.C5ChangesThreshholdLastDatetime;
            this.CreateDatetime = model.CreateDatetime;
            this.UpdateDatetime = model.UpdateDatetime;
        }
    
        /// <summary>
        /// このインスタンスの各プロパティに、引数に指定されたDtSmartAnalysisResultのプロパティの値をコピーする
        /// </summary>
        /// <param name="entity">コピー元のDtSmartAnalysisResult</param>
        public void CopyFrom(DtSmartAnalysisResult entity)
        {
            this.Sid = entity.Sid;
            this.EquipmentUid = entity.EquipmentUid;
            this.DiskSerialNumber = entity.DiskSerialNumber;
            this.C5RawData = entity.C5RawData;
            this.C5RawDataChanges = entity.C5RawDataChanges;
            this.C5ChangesThreshhold = entity.C5ChangesThreshhold;
            this.C5ChangesThreshholdOverCount = entity.C5ChangesThreshholdOverCount;
            this.C5ChangesThreshholdLastDatetime = entity.C5ChangesThreshholdLastDatetime;
            this.CreateDatetime = entity.CreateDatetime;
            this.UpdateDatetime = entity.UpdateDatetime;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なRms.Server.Utility.Utility.Models.DtSmartAnalysisResult型に変換する。
        /// </summary>
        /// <returns></returns>
        public Rms.Server.Utility.Utility.Models.DtSmartAnalysisResult ToModel()
        {
            Rms.Server.Utility.Utility.Models.DtSmartAnalysisResult model = new Rms.Server.Utility.Utility.Models.DtSmartAnalysisResult();
            model.Sid = this.Sid;
            model.EquipmentUid = this.EquipmentUid;
            model.DiskSerialNumber = this.DiskSerialNumber;
            model.C5RawData = this.C5RawData;
            model.C5RawDataChanges = this.C5RawDataChanges;
            model.C5ChangesThreshhold = this.C5ChangesThreshhold;
            model.C5ChangesThreshholdOverCount = this.C5ChangesThreshholdOverCount;
            model.C5ChangesThreshholdLastDatetime = this.C5ChangesThreshholdLastDatetime;
            model.CreateDatetime = this.CreateDatetime;
            model.UpdateDatetime = this.UpdateDatetime;
    
            return model;
        }
    }
    
    /// <summary>
    /// DtSmartAnalysisResultのメタデータクラス
    /// </summary>
    public  class DtSmartAnalysisResultModelMetaData
    {
        [Key]
        [Required(ErrorMessage = "Sid is required.")]
        public long Sid { get; set; }
    
        [Required(ErrorMessage = "EquipmentUid is required.")]
        [StringLength(30, ErrorMessage = "EquipmentUid length should be less than 30 symbols.")]
        public string EquipmentUid { get; set; }
    
        [Required(ErrorMessage = "DiskSerialNumber is required.")]
        [StringLength(30, ErrorMessage = "DiskSerialNumber length should be less than 30 symbols.")]
        public string DiskSerialNumber { get; set; }
    
        [Required(ErrorMessage = "C5RawData is required.")]
        public long C5RawData { get; set; }
    
        [Required(ErrorMessage = "CreateDatetime is required.")]
        public System.DateTime CreateDatetime { get; set; }
    
        [Required(ErrorMessage = "UpdateDatetime is required.")]
        public System.DateTime UpdateDatetime { get; set; }
    
    }
}
