//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Utility.DBAccessor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    
    /// <summary>
    /// MtConnectStatusクラス
    /// </summary>
    [ModelMetadataType(typeof(MtConnectStatusModelMetaData))]
    public partial class MtConnectStatus
    {
        /// <summary>
        /// コンストラクタ
        /// </summary>
        public MtConnectStatus()
        {
        }
    
        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <param name="model">Rms.Server.Utility.Utility.Models.MtConnectStatusのインスタンス</param>
        public MtConnectStatus(Rms.Server.Utility.Utility.Models.MtConnectStatus model)
        {
            this.Sid = model.Sid;
            this.Code = model.Code;
            this.Description = model.Description;
            this.CreateDatetime = model.CreateDatetime;
        }
    
        /// <summary>
        /// このインスタンスの各プロパティに、引数に指定されたMtConnectStatusのプロパティの値をコピーする
        /// </summary>
        /// <param name="entity">コピー元のMtConnectStatus</param>
        public void CopyFrom(MtConnectStatus entity)
        {
            this.Sid = entity.Sid;
            this.Code = entity.Code;
            this.Description = entity.Description;
            this.CreateDatetime = entity.CreateDatetime;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なRms.Server.Utility.Utility.Models.MtConnectStatus型に変換する。
        /// </summary>
        /// <returns></returns>
        public Rms.Server.Utility.Utility.Models.MtConnectStatus ToModel()
        {
            Rms.Server.Utility.Utility.Models.MtConnectStatus model = new Rms.Server.Utility.Utility.Models.MtConnectStatus();
            model.Sid = this.Sid;
            model.Code = this.Code;
            model.Description = this.Description;
            model.CreateDatetime = this.CreateDatetime;
    
            return model;
        }
    }
    
    /// <summary>
    /// MtConnectStatusのメタデータクラス
    /// </summary>
    public  class MtConnectStatusModelMetaData
    {
        [Key]
        [Required(ErrorMessage = "Sid is required.")]
        public long Sid { get; set; }
    
        [Key]
        [Required(ErrorMessage = "Code is required.")]
        [StringLength(20, ErrorMessage = "Code length should be less than 20 symbols.")]
        public string Code { get; set; }
    
        [StringLength(200, ErrorMessage = "Description length should be less than 200 symbols.")]
        public string Description { get; set; }
    
        [Key]
        [Required(ErrorMessage = "CreateDatetime is required.")]
        public System.DateTime CreateDatetime { get; set; }
    
    }
}
