//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Utility.DBAccessor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    
    /// <summary>
    /// MtInstallTypeクラス
    /// </summary>
    [ModelMetadataType(typeof(MtInstallTypeModelMetaData))]
    public partial class MtInstallType
    {
        /// <summary>
        /// コンストラクタ
        /// </summary>
        public MtInstallType()
        {
        }
    
        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <param name="model">Rms.Server.Utility.Utility.Models.MtInstallTypeのインスタンス</param>
        public MtInstallType(Rms.Server.Utility.Utility.Models.MtInstallType model)
        {
            this.Sid = model.Sid;
            this.EquipmentTypeSid = model.EquipmentTypeSid;
            this.Code = model.Code;
            this.Description = model.Description;
            this.CreateDatetime = model.CreateDatetime;
        }
    
        /// <summary>
        /// このインスタンスの各プロパティに、引数に指定されたMtInstallTypeのプロパティの値をコピーする
        /// </summary>
        /// <param name="entity">コピー元のMtInstallType</param>
        public void CopyFrom(MtInstallType entity)
        {
            this.Sid = entity.Sid;
            this.EquipmentTypeSid = entity.EquipmentTypeSid;
            this.Code = entity.Code;
            this.Description = entity.Description;
            this.CreateDatetime = entity.CreateDatetime;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なRms.Server.Utility.Utility.Models.MtInstallType型に変換する。
        /// </summary>
        /// <returns></returns>
        public Rms.Server.Utility.Utility.Models.MtInstallType ToModel()
        {
            Rms.Server.Utility.Utility.Models.MtInstallType model = new Rms.Server.Utility.Utility.Models.MtInstallType();
            model.Sid = this.Sid;
            model.EquipmentTypeSid = this.EquipmentTypeSid;
            model.Code = this.Code;
            model.Description = this.Description;
            model.CreateDatetime = this.CreateDatetime;
    
            return model;
        }
    }
    
    /// <summary>
    /// MtInstallTypeのメタデータクラス
    /// </summary>
    public  class MtInstallTypeModelMetaData
    {
        [Key]
        [Required(ErrorMessage = "Sid is required.")]
        public long Sid { get; set; }
    
        [Key]
        [Required(ErrorMessage = "EquipmentTypeSid is required.")]
        public long EquipmentTypeSid { get; set; }
    
        [Key]
        [Required(ErrorMessage = "Code is required.")]
        [StringLength(30, ErrorMessage = "Code length should be less than 30 symbols.")]
        public string Code { get; set; }
    
        [StringLength(128, ErrorMessage = "Description length should be less than 128 symbols.")]
        public string Description { get; set; }
    
        [Key]
        [Required(ErrorMessage = "CreateDatetime is required.")]
        public System.DateTime CreateDatetime { get; set; }
    
    }
}
