using System;
using System.Collections.Generic;

namespace Rms.Server.Core.DBAccessor.Models
{
    public partial class DtDxaQcLog
    {
        public long Sid { get; set; }
        public long DeviceSid { get; set; }
        public string SourceEquipmentUid { get; set; }
        public string StudyInstanceUid { get; set; }
        public string SopInstanceUid { get; set; }
        public DateTime? StudyDatetime { get; set; }
        public DateTime? MeasureDatetime { get; set; }
        public string PanelSerialId { get; set; }
        public byte? TechniqueCode { get; set; }
        public byte? TypeName { get; set; }
        public long? QcResult { get; set; }
        public double? BmcDxaATest { get; set; }
        public double? BmcDxaBTest { get; set; }
        public double? BmcDxaCTest { get; set; }
        public double? AreaDxaATest { get; set; }
        public double? AreaDxaBTest { get; set; }
        public double? AreaDxaCTest { get; set; }
        public double? BmdDxaATest { get; set; }
        public double? BmdDxaBTest { get; set; }
        public double? BmdDxaCTest { get; set; }
        public double? BmdLinearityTest { get; set; }
        public double? QlCsiBoneATest { get; set; }
        public double? QlCsiBoneBTest { get; set; }
        public double? QlCsiBoneCTest { get; set; }
        public double? QlCsiSoftLaTest { get; set; }
        public double? QlCsiSoftLbTest { get; set; }
        public double? QlCsiSoftLcTest { get; set; }
        public double? QlCsiSoftRaTest { get; set; }
        public double? QlCsiSoftRbTest { get; set; }
        public double? QlCsiSoftRcTest { get; set; }
        public double? QlGosBoneATest { get; set; }
        public double? QlGosBoneBTest { get; set; }
        public double? QlGosBoneCTest { get; set; }
        public double? QlGosSoftLaTest { get; set; }
        public double? QlGosSoftLbTest { get; set; }
        public double? QlGosSoftLcTest { get; set; }
        public double? QlGosSoftRaTest { get; set; }
        public double? QlGosSoftRbTest { get; set; }
        public double? QlGosSoftRcTest { get; set; }
        public double? QlDxaBoneATest { get; set; }
        public double? QlDxaBoneBTest { get; set; }
        public double? QlDxaBoneCTest { get; set; }
        public double? QlDxaSoftLaTest { get; set; }
        public double? QlDxaSoftLbTest { get; set; }
        public double? QlDxaSoftLcTest { get; set; }
        public double? QlDxaSoftRaTest { get; set; }
        public double? QlDxaSoftRbTest { get; set; }
        public double? QlDxaSoftRcTest { get; set; }
        public double? StdCsiBoneATest { get; set; }
        public double? StdCsiBoneBTest { get; set; }
        public double? StdCsiBoneCTest { get; set; }
        public double? StdCsiSoftLaTest { get; set; }
        public double? StdCsiSoftLbTest { get; set; }
        public double? StdCsiSoftLcTest { get; set; }
        public double? StdCsiSoftRaTest { get; set; }
        public double? StdCsiSoftRbTest { get; set; }
        public double? StdCsiSoftRcTest { get; set; }
        public double? StdGosBoneATest { get; set; }
        public double? StdGosBoneBTest { get; set; }
        public double? StdGosBoneCTest { get; set; }
        public double? StdGosSoftLaTest { get; set; }
        public double? StdGosSoftLbTest { get; set; }
        public double? StdGosSoftLcTest { get; set; }
        public double? StdGosSoftRaTest { get; set; }
        public double? StdGosSoftRbTest { get; set; }
        public double? StdGosSoftRcTest { get; set; }
        public double? StdDxaBoneATest { get; set; }
        public double? StdDxaBoneBTest { get; set; }
        public double? StdDxaBoneCTest { get; set; }
        public double? StdDxaSoftLaTest { get; set; }
        public double? StdDxaSoftLbTest { get; set; }
        public double? StdDxaSoftLcTest { get; set; }
        public double? StdDxaSoftRaTest { get; set; }
        public double? StdDxaSoftRbTest { get; set; }
        public double? StdDxaSoftRcTest { get; set; }
        public double? BmdDxaABasvalTest { get; set; }
        public double? BmdDxaBBasvalTest { get; set; }
        public double? BmdDxaCBasvalTest { get; set; }
        public double? QlCsiBoneABasvalTest { get; set; }
        public double? QlCsiBoneBBasvalTest { get; set; }
        public double? QlCsiBoneCBasvalTest { get; set; }
        public double? QlCsiSoftLaBasvalTest { get; set; }
        public double? QlCsiSoftLbBasvalTest { get; set; }
        public double? QlCsiSoftLcBasvalTest { get; set; }
        public double? QlCsiSoftRaBasvalTest { get; set; }
        public double? QlCsiSoftRbBasvalTest { get; set; }
        public double? QlCsiSoftRcBasvalTest { get; set; }
        public double? QlGosBoneABasvalTest { get; set; }
        public double? QlGosBoneBBasvalTest { get; set; }
        public double? QlGosBoneCBasvalTest { get; set; }
        public double? QlGosSoftLaBasvalTest { get; set; }
        public double? QlGosSoftLbBasvalTest { get; set; }
        public double? QlGosSoftLcBasvalTest { get; set; }
        public double? QlGosSoftRaBasvalTest { get; set; }
        public double? QlGosSoftRbBasvalTest { get; set; }
        public double? QlGosSoftRcBasvalTest { get; set; }
        public double? QlDxaBoneABasvalTest { get; set; }
        public double? QlDxaBoneBBasvalTest { get; set; }
        public double? QlDxaBoneCBasvalTest { get; set; }
        public double? QlDxaSoftLaBasvalTest { get; set; }
        public double? QlDxaSoftLbBasvalTest { get; set; }
        public double? QlDxaSoftLcBasvalTest { get; set; }
        public double? QlDxaSoftRaBasvalTest { get; set; }
        public double? QlDxaSoftRbBasvalTest { get; set; }
        public double? QlDxaSoftRcBasvalTest { get; set; }
        public double? StdCsiBoneABasvalTest { get; set; }
        public double? StdCsiBoneBBasvalTest { get; set; }
        public double? StdCsiBoneCBasvalTest { get; set; }
        public double? StdCsiSoftLaBasvalTest { get; set; }
        public double? StdCsiSoftLbBasvalTest { get; set; }
        public double? StdCsiSoftLcBasvalTest { get; set; }
        public double? StdCsiSoftRaBasvalTest { get; set; }
        public double? StdCsiSoftRbBasvalTest { get; set; }
        public double? StdCsiSoftRcBasvalTest { get; set; }
        public double? StdGosBoneABasvalTest { get; set; }
        public double? StdGosBoneBBasvalTest { get; set; }
        public double? StdGosBoneCBasvalTest { get; set; }
        public double? StdGosSoftLaBasvalTest { get; set; }
        public double? StdGosSoftLbBasvalTest { get; set; }
        public double? StdGosSoftLcBasvalTest { get; set; }
        public double? StdGosSoftRaBasvalTest { get; set; }
        public double? StdGosSoftRbBasvalTest { get; set; }
        public double? StdGosSoftRcBasvalTest { get; set; }
        public double? StdDxaBoneABasvalTest { get; set; }
        public double? StdDxaBoneBBasvalTest { get; set; }
        public double? StdDxaBoneCBasvalTest { get; set; }
        public double? StdDxaSoftLaBasvalTest { get; set; }
        public double? StdDxaSoftLbBasvalTest { get; set; }
        public double? StdDxaSoftLcBasvalTest { get; set; }
        public double? StdDxaSoftRaBasvalTest { get; set; }
        public double? StdDxaSoftRbBasvalTest { get; set; }
        public double? StdDxaSoftRcBasvalTest { get; set; }
        public DateTime? CollectDatetime { get; set; }
        public string MessageId { get; set; }
        public DateTime CreateDatetime { get; set; }

        public DtDevice DeviceS { get; set; }
    }
}
