//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Operation.DBAccessor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    
    /// <summary>
    /// DtWorkReportExportクラス
    /// </summary>
    [ModelMetadataType(typeof(DtWorkReportExportModelMetaData))]
    public partial class DtWorkReportExport
    {
        /// <summary>
        /// コンストラクタ
        /// </summary>
        public DtWorkReportExport()
        {
        }
    
        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <param name="model">Rms.Server.Operation.Utility.Models.DtWorkReportExportのインスタンス</param>
        public DtWorkReportExport(Rms.Server.Operation.Utility.Models.DtWorkReportExport model)
        {
            this.Sid = model.Sid;
            this.StartWorkId = model.StartWorkId;
            this.StartWorkDatetime = model.StartWorkDatetime;
            this.EndWorkId = model.EndWorkId;
            this.EndWorkDatetime = model.EndWorkDatetime;
            this.FileName = model.FileName;
            this.CreateDatetime = model.CreateDatetime;
        }
    
        /// <summary>
        /// このインスタンスの各プロパティに、引数に指定されたDtWorkReportExportのプロパティの値をコピーする
        /// </summary>
        /// <param name="entity">コピー元のDtWorkReportExport</param>
        public void CopyFrom(DtWorkReportExport entity)
        {
            this.Sid = entity.Sid;
            this.StartWorkId = entity.StartWorkId;
            this.StartWorkDatetime = entity.StartWorkDatetime;
            this.EndWorkId = entity.EndWorkId;
            this.EndWorkDatetime = entity.EndWorkDatetime;
            this.FileName = entity.FileName;
            this.CreateDatetime = entity.CreateDatetime;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なRms.Server.Operation.Utility.Models.DtWorkReportExport型に変換する。
        /// </summary>
        /// <returns></returns>
        public Rms.Server.Operation.Utility.Models.DtWorkReportExport ToModel()
        {
            Rms.Server.Operation.Utility.Models.DtWorkReportExport model = new Rms.Server.Operation.Utility.Models.DtWorkReportExport();
            model.Sid = this.Sid;
            model.StartWorkId = this.StartWorkId;
            model.StartWorkDatetime = this.StartWorkDatetime;
            model.EndWorkId = this.EndWorkId;
            model.EndWorkDatetime = this.EndWorkDatetime;
            model.FileName = this.FileName;
            model.CreateDatetime = this.CreateDatetime;
    
            return model;
        }
    }
    
    /// <summary>
    /// DtWorkReportExportのメタデータクラス
    /// </summary>
    public  class DtWorkReportExportModelMetaData
    {
        [Key]
        [Required(ErrorMessage = "Sid is required.")]
        public long Sid { get; set; }
    
        [Required(ErrorMessage = "StartWorkId is required.")]
        public long StartWorkId { get; set; }
    
        [Required(ErrorMessage = "EndWorkId is required.")]
        public long EndWorkId { get; set; }
    
        [StringLength(256, ErrorMessage = "FileName length should be less than 256 symbols.")]
        public string FileName { get; set; }
    
        [Required(ErrorMessage = "CreateDatetime is required.")]
        public System.DateTime CreateDatetime { get; set; }
    
    }
}
