//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Operation.DBAccessor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    
    /// <summary>
    /// MtNetworkRouteクラス
    /// </summary>
    [ModelMetadataType(typeof(MtNetworkRouteModelMetaData))]
    public partial class MtNetworkRoute
    {
        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <param name="model">Rms.Server.Operation.Utility.Models.MtNetworkRouteのインスタンス</param>
        public MtNetworkRoute(Rms.Server.Operation.Utility.Models.MtNetworkRoute model)
        {
            this.Sid = model.Sid;
            this.Code = model.Code;
            this.NetworkName = model.NetworkName;
            this.NetworkBandwidth = model.NetworkBandwidth;
            this.CreateTimedate = model.CreateTimedate;
            this.UpdateDatetime = model.UpdateDatetime;
            this.DtEquipment = model.DtEquipment.Select(y => new DtEquipment(y)).ToHashSet();
        }
    
        /// <summary>
        /// このインスタンスの各プロパティに、引数に指定されたMtNetworkRouteのプロパティの値をコピーする
        /// </summary>
        /// <param name="entity">コピー元のMtNetworkRoute</param>
        public void CopyFrom(MtNetworkRoute entity)
        {
            this.Sid = entity.Sid;
            this.Code = entity.Code;
            this.NetworkName = entity.NetworkName;
            this.NetworkBandwidth = entity.NetworkBandwidth;
            this.CreateTimedate = entity.CreateTimedate;
            this.UpdateDatetime = entity.UpdateDatetime;
            this.DtEquipment = entity.DtEquipment;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なRms.Server.Operation.Utility.Models.MtNetworkRoute型に変換する。
        /// </summary>
        /// <returns></returns>
        public Rms.Server.Operation.Utility.Models.MtNetworkRoute ToModel()
        {
            Rms.Server.Operation.Utility.Models.MtNetworkRoute model = new Rms.Server.Operation.Utility.Models.MtNetworkRoute();
            model.Sid = this.Sid;
            model.Code = this.Code;
            model.NetworkName = this.NetworkName;
            model.NetworkBandwidth = this.NetworkBandwidth;
            model.CreateTimedate = this.CreateTimedate;
            model.UpdateDatetime = this.UpdateDatetime;
            model.DtEquipment = this.DtEquipment.Select(y => y.ToModel()).ToHashSet();
    
            return model;
        }
    }
    
    /// <summary>
    /// MtNetworkRouteのメタデータクラス
    /// </summary>
    public  class MtNetworkRouteModelMetaData
    {
        [Key]
        [Required(ErrorMessage = "Sid is required.")]
        public long Sid { get; set; }
    
        [Required(ErrorMessage = "Code is required.")]
        [StringLength(30, ErrorMessage = "Code length should be less than 30 symbols.")]
        [RegularExpression(@"^[\x20-\x7e]+$", ErrorMessage = "Code is only allowed for ASCII code characters.")]
        public string Code { get; set; }
    
        [StringLength(50, ErrorMessage = "NetworkName length should be less than 50 symbols.")]
        public string NetworkName { get; set; }
    
        [Required(ErrorMessage = "CreateTimedate is required.")]
        public System.DateTime CreateTimedate { get; set; }
    
        [Required(ErrorMessage = "UpdateDatetime is required.")]
        public System.DateTime UpdateDatetime { get; set; }
    
    }
}
