//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Core.Utility.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rms.Server.Core.Utility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFC_001 {
            get {
                return ResourceManager.GetString("CO_API_DFC_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFC_002 {
            get {
                return ResourceManager.GetString("CO_API_DFC_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信ファイル情報の登録に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFC_003 {
            get {
                return ResourceManager.GetString("CO_API_DFC_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信ファイル情報を登録しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFC_004 {
            get {
                return ResourceManager.GetString("CO_API_DFC_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFD_001 {
            get {
                return ResourceManager.GetString("CO_API_DFD_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFD_002 {
            get {
                return ResourceManager.GetString("CO_API_DFD_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信ファイル情報の削除に失敗しました。配信前状態ではない配信ファイル情報を削除しようとしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFD_003 {
            get {
                return ResourceManager.GetString("CO_API_DFD_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信ファイル情報の削除に失敗しました。別プロセスにより更新された配信ファイル情報を削除しようとしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFD_004 {
            get {
                return ResourceManager.GetString("CO_API_DFD_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信ファイル情報の削除に失敗しました。存在しない配信ファイル情報を削除しようとしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFD_005 {
            get {
                return ResourceManager.GetString("CO_API_DFD_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信ファイル情報の削除に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFD_006 {
            get {
                return ResourceManager.GetString("CO_API_DFD_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信ファイル情報を削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFD_007 {
            get {
                return ResourceManager.GetString("CO_API_DFD_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFU_001 {
            get {
                return ResourceManager.GetString("CO_API_DFU_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFU_002 {
            get {
                return ResourceManager.GetString("CO_API_DFU_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信ファイル情報の更新に失敗しました。配信前状態ではない配信ファイル情報を更新しようとしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFU_003 {
            get {
                return ResourceManager.GetString("CO_API_DFU_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信ファイル情報の更新に失敗しました。別プロセスにより更新された配信ファイル情報を上書きしようとしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFU_004 {
            get {
                return ResourceManager.GetString("CO_API_DFU_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信ファイル情報の更新に失敗しました。存在しない配信ファイル情報を更新しようとしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFU_005 {
            get {
                return ResourceManager.GetString("CO_API_DFU_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信ファイル情報の更新に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFU_006 {
            get {
                return ResourceManager.GetString("CO_API_DFU_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信ファイル情報を更新しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DFU_007 {
            get {
                return ResourceManager.GetString("CO_API_DFU_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGC_001 {
            get {
                return ResourceManager.GetString("CO_API_DGC_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGC_002 {
            get {
                return ResourceManager.GetString("CO_API_DGC_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信グループの登録に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGC_003 {
            get {
                return ResourceManager.GetString("CO_API_DGC_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信グループを登録しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGC_004 {
            get {
                return ResourceManager.GetString("CO_API_DGC_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGD_001 {
            get {
                return ResourceManager.GetString("CO_API_DGD_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGD_002 {
            get {
                return ResourceManager.GetString("CO_API_DGD_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信グループの削除に失敗しました。配信前状態ではない配信ファイル情報を削除しようとしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGD_003 {
            get {
                return ResourceManager.GetString("CO_API_DGD_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信グループの削除に失敗しました。別プロセスにより更新された配信グループを削除しようとしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGD_004 {
            get {
                return ResourceManager.GetString("CO_API_DGD_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信グループの削除に失敗しました。存在しない配信グループを削除しようとしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGD_005 {
            get {
                return ResourceManager.GetString("CO_API_DGD_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信グループの削除に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGD_006 {
            get {
                return ResourceManager.GetString("CO_API_DGD_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信グループを削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGD_007 {
            get {
                return ResourceManager.GetString("CO_API_DGD_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGU_001 {
            get {
                return ResourceManager.GetString("CO_API_DGU_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGU_002 {
            get {
                return ResourceManager.GetString("CO_API_DGU_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信グループの更新に失敗しました。配信前状態ではない配信グループを更新しようとしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGU_003 {
            get {
                return ResourceManager.GetString("CO_API_DGU_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信グループの更新に失敗しました。別プロセスにより更新された配信グループを上書きしようとしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGU_004 {
            get {
                return ResourceManager.GetString("CO_API_DGU_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信グループの更新に失敗しました。存在しない配信グループを更新しようとしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGU_005 {
            get {
                return ResourceManager.GetString("CO_API_DGU_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信グループの更新に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGU_006 {
            get {
                return ResourceManager.GetString("CO_API_DGU_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信グループを更新しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DGU_007 {
            get {
                return ResourceManager.GetString("CO_API_DGU_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DRC_001 {
            get {
                return ResourceManager.GetString("CO_API_DRC_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DRC_002 {
            get {
                return ResourceManager.GetString("CO_API_DRC_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象デバイス情報の取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DRC_003 {
            get {
                return ResourceManager.GetString("CO_API_DRC_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続先情報の取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DRC_004 {
            get {
                return ResourceManager.GetString("CO_API_DRC_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メッセージの送信に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DRC_006 {
            get {
                return ResourceManager.GetString("CO_API_DRC_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メッセージを送信しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DRC_007 {
            get {
                return ResourceManager.GetString("CO_API_DRC_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DSU_001 {
            get {
                return ResourceManager.GetString("CO_API_DSU_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DSU_002 {
            get {
                return ResourceManager.GetString("CO_API_DSU_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信ステータスの更新に失敗しました。別プロセスにより更新された配信ファイル情報を上書きしようとしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DSU_003 {
            get {
                return ResourceManager.GetString("CO_API_DSU_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信ステータスの更新に失敗しました。存在しない配信ファイル情報を更新しようとしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DSU_004 {
            get {
                return ResourceManager.GetString("CO_API_DSU_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信ステータスの更新に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DSU_005 {
            get {
                return ResourceManager.GetString("CO_API_DSU_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信ステータスを更新しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DSU_006 {
            get {
                return ResourceManager.GetString("CO_API_DSU_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DVC_001 {
            get {
                return ResourceManager.GetString("CO_API_DVC_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DVC_002 {
            get {
                return ResourceManager.GetString("CO_API_DVC_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB設定のためのパラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DVC_003 {
            get {
                return ResourceManager.GetString("CO_API_DVC_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機器情報の保存に失敗しました。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DVC_004 {
            get {
                return ResourceManager.GetString("CO_API_DVC_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設置設定ファイルの生成に失敗しました。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DVC_005 {
            get {
                return ResourceManager.GetString("CO_API_DVC_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設置設定ファイルのアップロードに失敗しました。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DVC_006 {
            get {
                return ResourceManager.GetString("CO_API_DVC_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機器情報の保存、設置設定ファイルのアップロードに成功しました。（エッジID = {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DVC_007 {
            get {
                return ResourceManager.GetString("CO_API_DVC_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DVU_001 {
            get {
                return ResourceManager.GetString("CO_API_DVU_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DVU_002 {
            get {
                return ResourceManager.GetString("CO_API_DVU_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB設定のためのパラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DVU_003 {
            get {
                return ResourceManager.GetString("CO_API_DVU_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機器情報の更新に失敗しました。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DVU_004 {
            get {
                return ResourceManager.GetString("CO_API_DVU_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設置設定ファイルの生成に失敗しました。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DVU_005 {
            get {
                return ResourceManager.GetString("CO_API_DVU_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設置設定ファイルのアップロードに失敗しました。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DVU_006 {
            get {
                return ResourceManager.GetString("CO_API_DVU_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機器情報の更新、設置設定ファイルのアップロードに成功しました。（エッジID = {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_API_DVU_007 {
            get {
                return ResourceManager.GetString("CO_API_DVU_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_BLC_BLC_001 {
            get {
                return ResourceManager.GetString("CO_BLC_BLC_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_BLC_BLC_002 {
            get {
                return ResourceManager.GetString("CO_BLC_BLC_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除対象のファイル情報一覧の取得に失敗しました。（検索条件：Container = {0} and FilePathPrefix= {1} and UpdateDatetime &lt; {2}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_BLC_BLC_003 {
            get {
                return ResourceManager.GetString("CO_BLC_BLC_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除対象のファイル情報が存在しません。（検索条件：Container = {0} and FilePathPrefix= {1} and UpdateDatetime &lt; {2}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_BLC_BLC_004 {
            get {
                return ResourceManager.GetString("CO_BLC_BLC_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル情報の削除に失敗しました。（ファイル情報：Container = {0}, FilePath = {1}, UpdateDatetime = {2}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_BLC_BLC_005 {
            get {
                return ResourceManager.GetString("CO_BLC_BLC_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの削除に失敗しました。（ファイル情報：Container = {0}, FilePath = {1}, UpdateDatetime = {2}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_BLC_BLC_006 {
            get {
                return ResourceManager.GetString("CO_BLC_BLC_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル情報とファイルを削除しました。（ファイル情報：Container = {0}, FilePath = {1}, UpdateDatetime = {2}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_BLC_BLC_007 {
            get {
                return ResourceManager.GetString("CO_BLC_BLC_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_BLI_BLI_001 {
            get {
                return ResourceManager.GetString("CO_BLI_BLI_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collectingからのファイルの取得に失敗しました。（検索条件：Container = {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_BLI_BLI_003 {
            get {
                return ResourceManager.GetString("CO_BLI_BLI_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   異常ファイルの保存に失敗しました。（ファイル情報：Container = {0}, FilePath = {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_BLI_BLI_004 {
            get {
                return ResourceManager.GetString("CO_BLI_BLI_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collectingからのファイルの削除に失敗しました。（ファイル情報：Container = {0}, FilePath = {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_BLI_BLI_005 {
            get {
                return ResourceManager.GetString("CO_BLI_BLI_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Core-mainへのファイルの保存に失敗しました。（ファイル情報：Container = {0}, FilePath = {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_BLI_BLI_006 {
            get {
                return ResourceManager.GetString("CO_BLI_BLI_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル情報の保存に失敗しました。（ファイル情報：Container = {0}, FilePath = {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_BLI_BLI_007 {
            get {
                return ResourceManager.GetString("CO_BLI_BLI_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Core-mainからのファイルの削除に失敗しました。（ファイル情報：Container = {0}, FilePath = {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_BLI_BLI_008 {
            get {
                return ResourceManager.GetString("CO_BLI_BLI_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インデックスを作成しました。（ファイル情報：Container = {0}, FilePath = {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_BLI_BLI_009 {
            get {
                return ResourceManager.GetString("CO_BLI_BLI_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DBC_DBC_001 {
            get {
                return ResourceManager.GetString("CO_DBC_DBC_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DBC_DBC_002 {
            get {
                return ResourceManager.GetString("CO_DBC_DBC_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの削除に失敗しました。（データ情報：{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DBC_DBC_003 {
            get {
                return ResourceManager.GetString("CO_DBC_DBC_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データを削除しました。（データ情報：{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DBC_DBC_004 {
            get {
                return ResourceManager.GetString("CO_DBC_DBC_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DLV_DLV_001 {
            get {
                return ResourceManager.GetString("CO_DLV_DLV_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。（配信グループSID = {0}, メッセージ = 「{1}」） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DLV_DLV_002 {
            get {
                return ResourceManager.GetString("CO_DLV_DLV_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。（ゲートウェイ機器エッジID = {0}, 機器UID = {1},メッセージ = 「{2}」） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DLV_DLV_003 {
            get {
                return ResourceManager.GetString("CO_DLV_DLV_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信グループの取得に失敗しました。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DLV_DLV_009 {
            get {
                return ResourceManager.GetString("CO_DLV_DLV_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信グループの更新に失敗しました。（配信グループSID = {0}, メッセージ = 「{1}」） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DLV_DLV_010 {
            get {
                return ResourceManager.GetString("CO_DLV_DLV_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オンラインなゲートウェイ機器の取得に失敗しました。（配信グループSID = {0}, メッセージ = 「{1}」） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DLV_DLV_011 {
            get {
                return ResourceManager.GetString("CO_DLV_DLV_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信メッセージ作成に失敗しました。（ゲートウェイ機器エッジID = {0}, 機器UID = {1},メッセージ = 「{2}」） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DLV_DLV_012 {
            get {
                return ResourceManager.GetString("CO_DLV_DLV_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲートウェイ機器が接続中のIoT Hubの情報取得中にエラーが発生しました。（ゲートウェイ機器エッジID = {0}, 機器UID = {1},メッセージ = 「{2}」） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DLV_DLV_013 {
            get {
                return ResourceManager.GetString("CO_DLV_DLV_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲートウェイ機器へのメッセージ送信依頼に失敗しました。（ゲートウェイ機器エッジID = {0}, 機器UID = {1},メッセージ = 「{2}」） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DLV_DLV_015 {
            get {
                return ResourceManager.GetString("CO_DLV_DLV_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信結果ステータスの更新に失敗しました。（ゲートウェイ機器エッジID = {0}, 機器UID = {1},メッセージ = 「{2}」） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DLV_DLV_016 {
            get {
                return ResourceManager.GetString("CO_DLV_DLV_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メッセージ送信処理が完了しました。（ゲートウェイ機器エッジID = {0}, 機器UID = {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DLV_DLV_017 {
            get {
                return ResourceManager.GetString("CO_DLV_DLV_017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDB_001 {
            get {
                return ResourceManager.GetString("CO_DSP_DDB_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDB_002 {
            get {
                return ResourceManager.GetString("CO_DSP_DDB_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理に失敗したMessageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDB_003 {
            get {
                return ResourceManager.GetString("CO_DSP_DDB_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したデバイスが存在しません（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDB_004 {
            get {
                return ResourceManager.GetString("CO_DSP_DDB_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの追加に成功しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDB_005 {
            get {
                return ResourceManager.GetString("CO_DSP_DDB_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EventDataの変換に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDB_006 {
            get {
                return ResourceManager.GetString("CO_DSP_DDB_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メッセージの「計測日時」が既存レコードよりも古かったためテーブルを更新しませんでした（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDB_007 {
            get {
                return ResourceManager.GetString("CO_DSP_DDB_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDB_008 {
            get {
                return ResourceManager.GetString("CO_DSP_DDB_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続ステータスの更新に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_001 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機器が接続中のIoT Hub情報を取得できませんでした（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_002 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機器のデバイスツインを取得できませんでした（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_003 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   端末情報を取得できませんでした（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_004 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリプト設定をできませんでした（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_005 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストレージ設定を取得できませんでした（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_006 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイスツインのストレージおよびスクリプトの設定の最新情報を確認できませんでした（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_007 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイスツインのDesiredプロパティを更新できませんでした（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_008 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機器をゲートウェイ機器とする配信情報を取得できませんでした（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_009 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信メッセージの作成に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_010 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機器へのメッセージ送信に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_011 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信結果ステータス更新に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_012 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_013 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IoT Hubへの機器接続に対応する処理に成功しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_014 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IoT Hubへの機器接続に対応する処理に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_015 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EventDataの変換に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_016 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続ステータスの更新に成功しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_017 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   イベント時刻がDBに記録された時刻より古いため更新しませんでした（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_019 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理に失敗したMessageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDC_020 {
            get {
                return ResourceManager.GetString("CO_DSP_DDC_020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDD_001 {
            get {
                return ResourceManager.GetString("CO_DSP_DDD_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDD_002 {
            get {
                return ResourceManager.GetString("CO_DSP_DDD_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理に失敗したMessageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDD_003 {
            get {
                return ResourceManager.GetString("CO_DSP_DDD_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したデバイスが存在しません（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDD_004 {
            get {
                return ResourceManager.GetString("CO_DSP_DDD_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの追加に成功しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDD_005 {
            get {
                return ResourceManager.GetString("CO_DSP_DDD_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EventDataの変換に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDD_006 {
            get {
                return ResourceManager.GetString("CO_DSP_DDD_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理済みのメッセージです（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDD_007 {
            get {
                return ResourceManager.GetString("CO_DSP_DDD_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDD_008 {
            get {
                return ResourceManager.GetString("CO_DSP_DDD_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDL_001 {
            get {
                return ResourceManager.GetString("CO_DSP_DDL_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDL_002 {
            get {
                return ResourceManager.GetString("CO_DSP_DDL_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理に失敗したMessageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDL_003 {
            get {
                return ResourceManager.GetString("CO_DSP_DDL_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したデバイスが存在しません（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDL_004 {
            get {
                return ResourceManager.GetString("CO_DSP_DDL_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの追加に成功しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDL_005 {
            get {
                return ResourceManager.GetString("CO_DSP_DDL_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EventDataの変換に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDL_006 {
            get {
                return ResourceManager.GetString("CO_DSP_DDL_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理済みのメッセージです（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDL_007 {
            get {
                return ResourceManager.GetString("CO_DSP_DDL_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDL_008 {
            get {
                return ResourceManager.GetString("CO_DSP_DDL_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDU_001 {
            get {
                return ResourceManager.GetString("CO_DSP_DDU_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDU_002 {
            get {
                return ResourceManager.GetString("CO_DSP_DDU_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理に失敗したMessageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDU_003 {
            get {
                return ResourceManager.GetString("CO_DSP_DDU_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したデバイスが存在しません（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDU_004 {
            get {
                return ResourceManager.GetString("CO_DSP_DDU_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの追加に成功しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDU_005 {
            get {
                return ResourceManager.GetString("CO_DSP_DDU_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EventDataの変換に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDU_006 {
            get {
                return ResourceManager.GetString("CO_DSP_DDU_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理済みのメッセージです（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDU_007 {
            get {
                return ResourceManager.GetString("CO_DSP_DDU_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDU_008 {
            get {
                return ResourceManager.GetString("CO_DSP_DDU_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDV_001 {
            get {
                return ResourceManager.GetString("CO_DSP_DDV_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDV_002 {
            get {
                return ResourceManager.GetString("CO_DSP_DDV_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理に失敗したMessageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDV_003 {
            get {
                return ResourceManager.GetString("CO_DSP_DDV_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したデバイスが存在しません（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDV_004 {
            get {
                return ResourceManager.GetString("CO_DSP_DDV_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータスの更新に成功しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDV_005 {
            get {
                return ResourceManager.GetString("CO_DSP_DDV_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EventDataの変換に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDV_006 {
            get {
                return ResourceManager.GetString("CO_DSP_DDV_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータスの更新に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDV_008 {
            get {
                return ResourceManager.GetString("CO_DSP_DDV_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   イベント時刻がDBに記録された時刻より古いため更新しませんでした（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DDV_009 {
            get {
                return ResourceManager.GetString("CO_DSP_DDV_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DEU_001 {
            get {
                return ResourceManager.GetString("CO_DSP_DEU_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DEU_002 {
            get {
                return ResourceManager.GetString("CO_DSP_DEU_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理に失敗したMessageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DEU_003 {
            get {
                return ResourceManager.GetString("CO_DSP_DEU_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したデバイスが存在しません（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DEU_004 {
            get {
                return ResourceManager.GetString("CO_DSP_DEU_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの追加に成功しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DEU_005 {
            get {
                return ResourceManager.GetString("CO_DSP_DEU_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EventDataの変換に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DEU_006 {
            get {
                return ResourceManager.GetString("CO_DSP_DEU_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理済みのメッセージです（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DEU_007 {
            get {
                return ResourceManager.GetString("CO_DSP_DEU_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DEU_008 {
            get {
                return ResourceManager.GetString("CO_DSP_DEU_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DID_001 {
            get {
                return ResourceManager.GetString("CO_DSP_DID_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DID_002 {
            get {
                return ResourceManager.GetString("CO_DSP_DID_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理に失敗したMessageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DID_003 {
            get {
                return ResourceManager.GetString("CO_DSP_DID_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したデバイスが存在しません（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DID_004 {
            get {
                return ResourceManager.GetString("CO_DSP_DID_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの追加に成功しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DID_005 {
            get {
                return ResourceManager.GetString("CO_DSP_DID_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EventDataの変換に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DID_006 {
            get {
                return ResourceManager.GetString("CO_DSP_DID_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理済みのメッセージです（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DID_007 {
            get {
                return ResourceManager.GetString("CO_DSP_DID_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DID_008 {
            get {
                return ResourceManager.GetString("CO_DSP_DID_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DII_001 {
            get {
                return ResourceManager.GetString("CO_DSP_DII_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DII_002 {
            get {
                return ResourceManager.GetString("CO_DSP_DII_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理に失敗したMessageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DII_003 {
            get {
                return ResourceManager.GetString("CO_DSP_DII_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したデバイスが存在しません（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DII_004 {
            get {
                return ResourceManager.GetString("CO_DSP_DII_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの追加に成功しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DII_005 {
            get {
                return ResourceManager.GetString("CO_DSP_DII_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EventDataの変換に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DII_006 {
            get {
                return ResourceManager.GetString("CO_DSP_DII_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理済みのメッセージです（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DII_007 {
            get {
                return ResourceManager.GetString("CO_DSP_DII_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DII_008 {
            get {
                return ResourceManager.GetString("CO_DSP_DII_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DIR_001 {
            get {
                return ResourceManager.GetString("CO_DSP_DIR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DIR_002 {
            get {
                return ResourceManager.GetString("CO_DSP_DIR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理に失敗したMessageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DIR_003 {
            get {
                return ResourceManager.GetString("CO_DSP_DIR_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したデバイスが存在しません（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DIR_004 {
            get {
                return ResourceManager.GetString("CO_DSP_DIR_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの追加に成功しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DIR_005 {
            get {
                return ResourceManager.GetString("CO_DSP_DIR_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EventDataの変換に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DIR_006 {
            get {
                return ResourceManager.GetString("CO_DSP_DIR_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理済みのメッセージです（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DIR_007 {
            get {
                return ResourceManager.GetString("CO_DSP_DIR_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DIR_008 {
            get {
                return ResourceManager.GetString("CO_DSP_DIR_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信グループのステータス更新に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DIR_009 {
            get {
                return ResourceManager.GetString("CO_DSP_DIR_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DPC_001 {
            get {
                return ResourceManager.GetString("CO_DSP_DPC_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DPC_002 {
            get {
                return ResourceManager.GetString("CO_DSP_DPC_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理に失敗したMessageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DPC_003 {
            get {
                return ResourceManager.GetString("CO_DSP_DPC_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したデバイスが存在しません（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DPC_004 {
            get {
                return ResourceManager.GetString("CO_DSP_DPC_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの追加または更新に成功しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DPC_005 {
            get {
                return ResourceManager.GetString("CO_DSP_DPC_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EventDataの変換に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DPC_006 {
            get {
                return ResourceManager.GetString("CO_DSP_DPC_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DPC_008 {
            get {
                return ResourceManager.GetString("CO_DSP_DPC_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メッセージの「確認日時」が既存レコードよりも古かったためテーブルを更新しませんでした（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DPC_009 {
            get {
                return ResourceManager.GetString("CO_DSP_DPC_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DPS_001 {
            get {
                return ResourceManager.GetString("CO_DSP_DPS_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DPS_002 {
            get {
                return ResourceManager.GetString("CO_DSP_DPS_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理に失敗したMessageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DPS_003 {
            get {
                return ResourceManager.GetString("CO_DSP_DPS_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したデバイスが存在しません（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DPS_004 {
            get {
                return ResourceManager.GetString("CO_DSP_DPS_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの追加に成功しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DPS_005 {
            get {
                return ResourceManager.GetString("CO_DSP_DPS_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EventDataの変換に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DPS_006 {
            get {
                return ResourceManager.GetString("CO_DSP_DPS_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メッセージの「計測日時」が既存レコードよりも古かったためテーブルを更新しませんでした（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DPS_007 {
            get {
                return ResourceManager.GetString("CO_DSP_DPS_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DPS_008 {
            get {
                return ResourceManager.GetString("CO_DSP_DPS_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DSV_001 {
            get {
                return ResourceManager.GetString("CO_DSP_DSV_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DSV_002 {
            get {
                return ResourceManager.GetString("CO_DSP_DSV_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理に失敗したMessageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DSV_003 {
            get {
                return ResourceManager.GetString("CO_DSP_DSV_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したデバイスが存在しません（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DSV_004 {
            get {
                return ResourceManager.GetString("CO_DSP_DSV_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの追加に成功しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DSV_005 {
            get {
                return ResourceManager.GetString("CO_DSP_DSV_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EventDataの変換に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DSV_006 {
            get {
                return ResourceManager.GetString("CO_DSP_DSV_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理済みのメッセージです（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DSV_007 {
            get {
                return ResourceManager.GetString("CO_DSP_DSV_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DSV_008 {
            get {
                return ResourceManager.GetString("CO_DSP_DSV_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DTC_001 {
            get {
                return ResourceManager.GetString("CO_DSP_DTC_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DTC_002 {
            get {
                return ResourceManager.GetString("CO_DSP_DTC_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理に失敗したMessageの保存に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DTC_003 {
            get {
                return ResourceManager.GetString("CO_DSP_DTC_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したデバイスが存在しません（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DTC_004 {
            get {
                return ResourceManager.GetString("CO_DSP_DTC_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブルの更新に成功しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DTC_005 {
            get {
                return ResourceManager.GetString("CO_DSP_DTC_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EventDataの変換に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DTC_006 {
            get {
                return ResourceManager.GetString("CO_DSP_DTC_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブルの更新に失敗しました（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO_DSP_DTC_008 {
            get {
                return ResourceManager.GetString("CO_DSP_DTC_008", resourceCulture);
            }
        }
    }
}
