//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Operation.Utility.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rms.Server.Operation.Utility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_ALR_ALR_001 {
            get {
                return ResourceManager.GetString("OP_ALR_ALR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{1}）（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_ALR_ALR_002 {
            get {
                return ResourceManager.GetString("OP_ALR_ALR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームデータの重複チェックに失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_ALR_ALR_003 {
            get {
                return ResourceManager.GetString("OP_ALR_ALR_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームデータが既に登録済みです。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_ALR_ALR_004 {
            get {
                return ResourceManager.GetString("OP_ALR_ALR_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム設定の取得に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_ALR_ALR_005 {
            get {
                return ResourceManager.GetString("OP_ALR_ALR_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メール間隔日数の確認に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_ALR_ALR_006 {
            get {
                return ResourceManager.GetString("OP_ALR_ALR_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールキューの登録に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_ALR_ALR_007 {
            get {
                return ResourceManager.GetString("OP_ALR_ALR_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールキューを登録しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_ALR_ALR_008 {
            get {
                return ResourceManager.GetString("OP_ALR_ALR_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームデータの保存に失敗しました。（DtAlarm: {1}）（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_ALR_ALR_009 {
            get {
                return ResourceManager.GetString("OP_ALR_ALR_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームデータを保存しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_ALR_ALR_010 {
            get {
                return ResourceManager.GetString("OP_ALR_ALR_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再送用メッセージの保存に失敗しました。（message-id: {0}）（message: {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_ALR_ALR_011 {
            get {
                return ResourceManager.GetString("OP_ALR_ALR_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_ALR_ALR_012 {
            get {
                return ResourceManager.GetString("OP_ALR_ALR_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_DBC_DBC_001 {
            get {
                return ResourceManager.GetString("OP_DBC_DBC_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_DBC_DBC_002 {
            get {
                return ResourceManager.GetString("OP_DBC_DBC_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの削除に失敗しました。（データ情報：{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_DBC_DBC_003 {
            get {
                return ResourceManager.GetString("OP_DBC_DBC_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データを削除しました。（データ情報：{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_DBC_DBC_004 {
            get {
                return ResourceManager.GetString("OP_DBC_DBC_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_MLS_MLS_001 {
            get {
                return ResourceManager.GetString("OP_MLS_MLS_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メール送信の依頼に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_MLS_MLS_002 {
            get {
                return ResourceManager.GetString("OP_MLS_MLS_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メール送信を依頼しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_MLS_MLS_003 {
            get {
                return ResourceManager.GetString("OP_MLS_MLS_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再送用メッセージの保存に失敗しました。（message: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_MLS_MLS_004 {
            get {
                return ResourceManager.GetString("OP_MLS_MLS_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_MLS_MLS_005 {
            get {
                return ResourceManager.GetString("OP_MLS_MLS_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OP_MLS_MLS_006 {
            get {
                return ResourceManager.GetString("OP_MLS_MLS_006", resourceCulture);
            }
        }
    }
}
