//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Utility.Utility.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtAlmilogAnalysisConfig
    {
        public long Sid { get; set; }
    
        public string DetectorName { get; set; }
    
        public bool IsNormalized { get; set; }
    
        public double MinSlopeValue { get; set; }
    
        public double MiddleSlopeValue { get; set; }
    
        public double MaxSlopeValue { get; set; }
    
        public int LowVoltageAreaValue { get; set; }
    
        public int HighVoltageAreaValue { get; set; }
    
        public string AreaStandardData { get; set; }
    
        public System.DateTime CreateDatetime { get; set; }
    
        public System.DateTime UpdateDatetime { get; set; }
    
    }
}
