//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Utility.Utility.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtBloclogAnalysisResult
    {
        public long Sid { get; set; }
    
        public string EquipmentUid { get; set; }
    
        public string BloclogMonth { get; set; }
    
        public string DetectorName { get; set; }
    
        public string DetectorId { get; set; }
    
        public Nullable<int> GpValue { get; set; }
    
        public string ImageFileName { get; set; }
    
        public Nullable<short> FileNameNo { get; set; }
    
        public string ShadingResult { get; set; }
    
        public Nullable<double> ShadingResultMcv { get; set; }
    
        public Nullable<double> ShadingResultScv { get; set; }
    
        public Nullable<double> ShadingResultMcvSv { get; set; }
    
        public Nullable<double> ShadingResultScvSv1 { get; set; }
    
        public Nullable<double> ShadingResultScvSv2 { get; set; }
    
        public Nullable<bool> ImageType { get; set; }
    
        public Nullable<int> ImageSize { get; set; }
    
        public Nullable<bool> IsBillTarget { get; set; }
    
        public string LogFileName { get; set; }
    
        public System.DateTime CreateDatetime { get; set; }
    
    }
}
