//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Utility.Utility.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtDevice
    {
        public long Sid { get; set; }
    
        public Nullable<long> EquipmentModelSid { get; set; }
    
        public long InstallTypeSid { get; set; }
    
        public long ConnectStatusSid { get; set; }
    
        public System.Guid EdgeId { get; set; }
    
        public string EquipmentUid { get; set; }
    
        public string RemoteConnectUid { get; set; }
    
        public string RmsSoftVersion { get; set; }
    
        public Nullable<System.DateTime> ConnectStartDatetime { get; set; }
    
        public Nullable<System.DateTime> ConnectUpdateDatetime { get; set; }
    
        public System.DateTime CreateDatetime { get; set; }
    
        public System.DateTime UpdateDatetime { get; set; }
    
    }
}
