//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Utility.Utility.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtSmartAnalysisResult
    {
        public long Sid { get; set; }
    
        public string EquipmentUid { get; set; }
    
        public string DiskSerialNumber { get; set; }
    
        public long C5RawData { get; set; }
    
        public Nullable<short> C5RawDataChanges { get; set; }
    
        public Nullable<short> C5ChangesThreshhold { get; set; }
    
        public Nullable<short> C5ChangesThreshholdOverCount { get; set; }
    
        public Nullable<System.DateTime> C5ChangesThreshholdLastDatetime { get; set; }
    
        public System.DateTime CreateDatetime { get; set; }
    
        public System.DateTime UpdateDatetime { get; set; }
    
    }
}
