set MS_BUILD=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe

set RESTORE_OPTION=-t:restore

set BUILD_CONFIGURATION=Release
set BUILD_PLATFORM=Any CPU
set BUILD_SDK=netcoreapp2.1
set BUILD_OPTION=/t:clean;rebuild /p:Configuration=%BUILD_CONFIGURATION%;Platform="%BUILD_PLATFORM%"

set DLL_PATH=bin\%BUILD_PLATFORM%\%BUILD_CONFIGURATION%\%BUILD_SDK%

set CORE_ABSTRACTION_DLL_NAME=Rms.Server.Core.Abstraction.dll
set CORE_ABSTRACTION_PATH=..\Rms.Server.Core\Abstraction
set CORE_ABSTRACTION_DLL_PATH=%CORE_ABSTRACTION_PATH%\%DLL_PATH%

set CORE_SERVICE_DLL_NAME=Rms.Server.Core.Service.dll
set CORE_SERVICE_PATH=..\Rms.Server.Core\Service
set CORE_SERVICE_DLL_PATH=%CORE_SERVICE_PATH%\%DLL_PATH%

set CORE_UTILITY_DLL_NAME=Rms.Server.Core.Utility.dll
set CORE_UTILITY_PATH=..\Rms.Server.Core\Utility
set CORE_UTILITY_DLL_PATH=%CORE_UTILITY_PATH%\%DLL_PATH%

set OPERATION_ROOT=..\Rms.Server.Operation

set OPERATION_UTILITY_DLL_NAME=Rms.Server.Operation.Utility.dll
set OPERATION_UTILITY_PATH=%OPERATION_ROOT%\Utility
set OPERATION_UTILITY_DLL_PATH=%OPERATION_UTILITY_PATH%\%DLL_PATH%

set OPERATION_BUILD_BAT_NAME=LibBuild.bat
set OPERATION_BUILD_BAT_PATH=%OPERATION_ROOT%
set OPERATION_BUILD_BAT=%OPERATION_BUILD_BAT_PATH%\%OPERATION_BUILD_BAT_NAME%

set UTILITY_LIB_PATH=.\lib
set CURRENT_DIR=%~dp0

cd %OPERATION_BUILD_BAT_PATH%
call %OPERATION_BUILD_BAT%

cd %CURRENT_DIR%
"%MS_BUILD%" %RESTORE_OPTION% "%CORE_ABSTRACTION_PATH%"
"%MS_BUILD%" "%CORE_ABSTRACTION_PATH%" %BUILD_OPTION%

"%MS_BUILD%" %RESTORE_OPTION% "%CORE_SERVICE_PATH%"
"%MS_BUILD%" "%CORE_SERVICE_PATH%" %BUILD_OPTION%

"%MS_BUILD%" %RESTORE_OPTION% "%CORE_UTILITY_PATH%"
"%MS_BUILD%" "%CORE_UTILITY_PATH%" %BUILD_OPTION%

"%MS_BUILD%" %RESTORE_OPTION% "%OPERATION_UTILITY_PATH%"
"%MS_BUILD%" "%OPERATION_UTILITY_PATH%" %BUILD_OPTION%

robocopy "%CORE_ABSTRACTION_DLL_PATH%" "%UTILITY_LIB_PATH%" %CORE_ABSTRACTION_DLL_NAME%
robocopy "%CORE_SERVICE_DLL_PATH%" "%UTILITY_LIB_PATH%" %CORE_SERVICE_DLL_NAME%
robocopy "%CORE_UTILITY_DLL_PATH%" "%UTILITY_LIB_PATH%" %CORE_UTILITY_DLL_NAME%
robocopy "%OPERATION_UTILITY_DLL_PATH%" "%UTILITY_LIB_PATH%" %OPERATION_UTILITY_DLL_NAME%
