//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Operation.Utility.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtAlarmConfig
    {
        public long Sid { get; set; }
    
        public byte AlarmLevelFrom { get; set; }
    
        public byte AlarmLevelTo { get; set; }
    
        public string MailAddress { get; set; }
    
        public Nullable<byte> MailSendingInterval { get; set; }
    
        public string Description { get; set; }
    
        public System.DateTime CreateDatetime { get; set; }
    
        public System.DateTime UpdateDatetime { get; set; }
    
        public byte[] RowVersion { get; set; }
    
    }
}
