//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Operation.Utility.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtAlarm
    {
        public long Sid { get; set; }
    
        public long EquipmentSid { get; set; }
    
        public string TypeCode { get; set; }
    
        public string ErrorCode { get; set; }
    
        public Nullable<byte> AlarmLevel { get; set; }
    
        public string AlarmTitle { get; set; }
    
        public string AlarmDescription { get; set; }
    
        public Nullable<System.DateTime> AlarmDatetime { get; set; }
    
        public string AlarmDefId { get; set; }
    
        public Nullable<System.DateTime> EventDatetime { get; set; }
    
        public Nullable<bool> HasMail { get; set; }
    
        public string MessageId { get; set; }
    
        public System.DateTime CreateDatetime { get; set; }
    
        public virtual DtEquipment DtEquipment { get; set; }
    
    }
}
