//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Operation.Utility.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtEquipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DtEquipment()
        {
            this.DtAlarm = new HashSet<DtAlarm>();
            this.DtEquipment1 = new HashSet<DtEquipment>();
            this.DtEquipment11 = new HashSet<DtEquipment>();
        }
        public long Sid { get; set; }
    
        public long InstallBaseSid { get; set; }
    
        public long NetworkRouteSid { get; set; }
    
        public Nullable<long> TopEquipmentSid { get; set; }
    
        public Nullable<long> ParentEquipmentSid { get; set; }
    
        public byte Hierarchy { get; set; }
    
        public string HierarchyPath { get; set; }
    
        public string HierarchyOrder { get; set; }
    
        public string EquipmentNumber { get; set; }
    
        public string HostName { get; set; }
    
        public string IpAddress { get; set; }
    
        public string Description { get; set; }
    
        public Nullable<bool> IsDeleted { get; set; }
    
        public System.DateTime CreateDatetime { get; set; }
    
        public System.DateTime UpdateDatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtAlarm> DtAlarm { get; set; }
    
        public virtual DtInstallBase DtInstallBase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtEquipment> DtEquipment1 { get; set; }
    
        public virtual DtEquipment DtEquipment2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtEquipment> DtEquipment11 { get; set; }
    
        public virtual DtEquipment DtEquipment3 { get; set; }
    
        public virtual MtNetworkRoute MtNetworkRoute { get; set; }
    
    }
}
