//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Operation.Utility.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtInstallBase
    {
        public long Sid { get; set; }
    
        public string EquipmentNumber { get; set; }
    
        public string EquipmentName { get; set; }
    
        public string EquipmentSerialNumber { get; set; }
    
        public Nullable<System.DateTime> InstallCompleteDate { get; set; }
    
        public string InstallFeatures { get; set; }
    
        public Nullable<int> CustomerNumber { get; set; }
    
        public string CustomerName { get; set; }
    
        public string ZipCode { get; set; }
    
        public string Address { get; set; }
    
        public string Telephone { get; set; }
    
        public string ScssName { get; set; }
    
        public string Outsourcer { get; set; }
    
        public Nullable<System.DateTime> RemoveDate { get; set; }
    
        public Nullable<System.DateTime> ImportCreateDatetime { get; set; }
    
        public Nullable<System.DateTime> ImportUpdateDatetime { get; set; }
    
        public Nullable<System.DateTime> CreateDatetime { get; set; }
    
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual DtEquipment DtEquipment { get; set; }
    
    }
}
