//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Operation.Utility.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MtNetworkRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MtNetworkRoute()
        {
            this.DtEquipment = new HashSet<DtEquipment>();
        }
        public long Sid { get; set; }
    
        public string Code { get; set; }
    
        public string NetworkName { get; set; }
    
        public Nullable<int> NetworkBandwidth { get; set; }
    
        public System.DateTime CreateTimedate { get; set; }
    
        public System.DateTime UpdateDatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtEquipment> DtEquipment { get; set; }
    
    }
}
