//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Core.DBAccessor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    
    /// <summary>
    /// DtDeliveryResultクラス
    /// </summary>
    [ModelMetadataType(typeof(DtDeliveryResultModelMetaData))]
    public partial class DtDeliveryResult
    {
        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <param name="model">Utility.Models.Entites.DtDeliveryResultのインスタンス</param>
        public DtDeliveryResult(Utility.Models.Entites.DtDeliveryResult model)
        {
            this.Sid = model.Sid;
            this.DeviceSid = model.DeviceSid;
            this.GwDeviceSid = model.GwDeviceSid;
            this.DeliveryGroupSid = model.DeliveryGroupSid;
            this.CreateDatetime = model.CreateDatetime;
            this.DtInstallResult = model.DtInstallResult.Select(y => new DtInstallResult(y)).ToHashSet();
            this.DeliveryGroupS = model.DtDeliveryGroup == null ?
                null :
                new DtDeliveryGroup(model.DtDeliveryGroup);
            this.GwDeviceS = model.DtDevice == null ?
                null :
                new DtDevice(model.DtDevice);
            this.DeviceS = model.DtDevice1 == null ?
                null :
                new DtDevice(model.DtDevice1);
        }
    
        /// <summary>
        /// このインスタンスの各プロパティに、引数に指定されたDtDeliveryResultのプロパティの値をコピーする
        /// </summary>
        /// <param name="entity">コピー元のDtDeliveryResult</param>
        public void CopyFrom(DtDeliveryResult entity)
        {
            this.Sid = entity.Sid;
            this.DeviceSid = entity.DeviceSid;
            this.GwDeviceSid = entity.GwDeviceSid;
            this.DeliveryGroupSid = entity.DeliveryGroupSid;
            this.CreateDatetime = entity.CreateDatetime;
            this.DtInstallResult = entity.DtInstallResult;
            this.DeliveryGroupS = entity.DeliveryGroupS;
            this.GwDeviceS = entity.GwDeviceS;
            this.DeviceS = entity.DeviceS;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.DtDeliveryResult型に変換する。
        /// 各変換メソッド共通部分
        /// </summary>
        /// <returns></returns>
        private Utility.Models.Entites.DtDeliveryResult ToModelCommonPart()
        {
            Utility.Models.Entites.DtDeliveryResult model = new Utility.Models.Entites.DtDeliveryResult();
            model.Sid = this.Sid;
            model.DeviceSid = this.DeviceSid;
            model.GwDeviceSid = this.GwDeviceSid;
            model.DeliveryGroupSid = this.DeliveryGroupSid;
            model.CreateDatetime = this.CreateDatetime;
            return model;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.DtDeliveryResult型に変換する。
        /// </summary>
        /// <returns></returns>
        public Utility.Models.Entites.DtDeliveryResult ToModel()
        {
            Utility.Models.Entites.DtDeliveryResult model = ToModelCommonPart();
            model.DtInstallResult = this.DtInstallResult.Select(y => y.ToChildModel(this.GetType())).ToHashSet();
            model.DtDeliveryGroup = this.DeliveryGroupS?.ToParentModel(this.GetType());
            model.DtDevice = this.GwDeviceS?.ToParentModel(this.GetType());
            model.DtDevice1 = this.DeviceS?.ToParentModel(this.GetType());
    
            return model;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.DtDeliveryResult型に変換する。
        /// 親エンティティとして生成するため、子エンティティの情報はもたない
        /// </summary>
        /// <returns></returns>
        public Utility.Models.Entites.DtDeliveryResult ToParentModel(Type childType)
        {
            Utility.Models.Entites.DtDeliveryResult model = ToModelCommonPart();
            // 親子間の参照無限ループを避けるためにタイプチェック
            if (this.DtInstallResult.LastOrDefault()?.GetType() != childType)
            {
                model.DtInstallResult = this.DtInstallResult.Select(y => y.ToChildModel(this.GetType())).ToHashSet();
            }
            model.DtDeliveryGroup = this.DeliveryGroupS?.ToParentModel(this.GetType());
            model.DtDevice = this.GwDeviceS?.ToParentModel(this.GetType());
            model.DtDevice1 = this.DeviceS?.ToParentModel(this.GetType());
    
            return model;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.DtDeliveryResult型に変換する。
        /// 子エンティティとして生成するため、親エンティティの情報をもたない
        /// </summary>
        /// <returns></returns>
        public Utility.Models.Entites.DtDeliveryResult ToChildModel(Type parentType)
        {
            Utility.Models.Entites.DtDeliveryResult model = ToModelCommonPart();
            model.DtInstallResult = this.DtInstallResult.Select(y => y.ToChildModel(this.GetType())).ToHashSet();
            // 親子間の参照無限ループを避けるためにタイプチェック
            if (this.DeliveryGroupS?.GetType() != parentType)
            {
                model.DtDeliveryGroup = this.DeliveryGroupS?.ToParentModel(this.GetType());
            }
            if (this.GwDeviceS?.GetType() != parentType)
            {
                model.DtDevice = this.GwDeviceS?.ToParentModel(this.GetType());
            }
            if (this.DeviceS?.GetType() != parentType)
            {
                model.DtDevice1 = this.DeviceS?.ToParentModel(this.GetType());
            }
    
            return model;
        }
    }
    
    /// <summary>
    /// DtDeliveryResultのメタデータクラス
    /// </summary>
    public  class DtDeliveryResultModelMetaData
    {
        [Key]
        [Required(ErrorMessage = "Sid is required.")]
        public long Sid { get; set; }
    
        [Required(ErrorMessage = "DeviceSid is required.")]
        public long DeviceSid { get; set; }
    
        [Required(ErrorMessage = "GwDeviceSid is required.")]
        public long GwDeviceSid { get; set; }
    
        [Required(ErrorMessage = "DeliveryGroupSid is required.")]
        public long DeliveryGroupSid { get; set; }
    
        [Required(ErrorMessage = "CreateDatetime is required.")]
        public System.DateTime CreateDatetime { get; set; }
    
    }
}
