//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Core.DBAccessor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    
    /// <summary>
    /// DtDiskDriveクラス
    /// </summary>
    [ModelMetadataType(typeof(DtDiskDriveModelMetaData))]
    public partial class DtDiskDrive
    {
        /// <summary>
        /// コンストラクタ
        /// </summary>
        public DtDiskDrive()
        {
        }
    
        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <param name="model">Utility.Models.Entites.DtDiskDriveのインスタンス</param>
        public DtDiskDrive(Utility.Models.Entites.DtDiskDrive model)
        {
            this.Sid = model.Sid;
            this.DeviceSid = model.DeviceSid;
            this.SourceEquipmentUid = model.SourceEquipmentUid;
            this.Model = model.Model;
            this.MediaType = model.MediaType;
            this.InterfaceType = model.InterfaceType;
            this.SerialNumber = model.SerialNumber;
            this.SmartAttributeInfo = model.SmartAttributeInfo;
            this.CollectDatetime = model.CollectDatetime;
            this.MessageId = model.MessageId;
            this.CreateDatetime = model.CreateDatetime;
            this.DeviceS = model.DtDevice == null ?
                null :
                new DtDevice(model.DtDevice);
        }
    
        /// <summary>
        /// このインスタンスの各プロパティに、引数に指定されたDtDiskDriveのプロパティの値をコピーする
        /// </summary>
        /// <param name="entity">コピー元のDtDiskDrive</param>
        public void CopyFrom(DtDiskDrive entity)
        {
            this.Sid = entity.Sid;
            this.DeviceSid = entity.DeviceSid;
            this.SourceEquipmentUid = entity.SourceEquipmentUid;
            this.Model = entity.Model;
            this.MediaType = entity.MediaType;
            this.InterfaceType = entity.InterfaceType;
            this.SerialNumber = entity.SerialNumber;
            this.SmartAttributeInfo = entity.SmartAttributeInfo;
            this.CollectDatetime = entity.CollectDatetime;
            this.MessageId = entity.MessageId;
            this.CreateDatetime = entity.CreateDatetime;
            this.DeviceS = entity.DeviceS;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.DtDiskDrive型に変換する。
        /// 各変換メソッド共通部分
        /// </summary>
        /// <returns></returns>
        private Utility.Models.Entites.DtDiskDrive ToModelCommonPart()
        {
            Utility.Models.Entites.DtDiskDrive model = new Utility.Models.Entites.DtDiskDrive();
            model.Sid = this.Sid;
            model.DeviceSid = this.DeviceSid;
            model.SourceEquipmentUid = this.SourceEquipmentUid;
            model.Model = this.Model;
            model.MediaType = this.MediaType;
            model.InterfaceType = this.InterfaceType;
            model.SerialNumber = this.SerialNumber;
            model.SmartAttributeInfo = this.SmartAttributeInfo;
            model.CollectDatetime = this.CollectDatetime;
            model.MessageId = this.MessageId;
            model.CreateDatetime = this.CreateDatetime;
            return model;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.DtDiskDrive型に変換する。
        /// </summary>
        /// <returns></returns>
        public Utility.Models.Entites.DtDiskDrive ToModel()
        {
            Utility.Models.Entites.DtDiskDrive model = ToModelCommonPart();
            model.DtDevice = this.DeviceS?.ToParentModel(this.GetType());
    
            return model;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.DtDiskDrive型に変換する。
        /// 親エンティティとして生成するため、子エンティティの情報はもたない
        /// </summary>
        /// <returns></returns>
        public Utility.Models.Entites.DtDiskDrive ToParentModel(Type childType)
        {
            Utility.Models.Entites.DtDiskDrive model = ToModelCommonPart();
            model.DtDevice = this.DeviceS?.ToParentModel(this.GetType());
    
            return model;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.DtDiskDrive型に変換する。
        /// 子エンティティとして生成するため、親エンティティの情報をもたない
        /// </summary>
        /// <returns></returns>
        public Utility.Models.Entites.DtDiskDrive ToChildModel(Type parentType)
        {
            Utility.Models.Entites.DtDiskDrive model = ToModelCommonPart();
            // 親子間の参照無限ループを避けるためにタイプチェック
            if (this.DeviceS?.GetType() != parentType)
            {
                model.DtDevice = this.DeviceS?.ToParentModel(this.GetType());
            }
    
            return model;
        }
    }
    
    /// <summary>
    /// DtDiskDriveのメタデータクラス
    /// </summary>
    public  class DtDiskDriveModelMetaData
    {
        [Key]
        [Required(ErrorMessage = "Sid is required.")]
        public long Sid { get; set; }
    
        [Required(ErrorMessage = "DeviceSid is required.")]
        public long DeviceSid { get; set; }
    
        [StringLength(30, ErrorMessage = "SourceEquipmentUid length should be less than 30 symbols.")]
        [RegularExpression(Utility.Const.AsciiCodeCharactersReg, ErrorMessage = "SourceEquipmentUid is only allowed for ASCII code characters.")]
        public string SourceEquipmentUid { get; set; }
    
        [StringLength(100, ErrorMessage = "Model length should be less than 100 symbols.")]
        [RegularExpression(Utility.Const.AsciiCodeCharactersReg, ErrorMessage = "Model is only allowed for ASCII code characters.")]
        public string Model { get; set; }
    
        [StringLength(20, ErrorMessage = "MediaType length should be less than 20 symbols.")]
        [RegularExpression(Utility.Const.AsciiCodeCharactersReg, ErrorMessage = "MediaType is only allowed for ASCII code characters.")]
        public string MediaType { get; set; }
    
        [StringLength(30, ErrorMessage = "InterfaceType length should be less than 30 symbols.")]
        [RegularExpression(Utility.Const.AsciiCodeCharactersReg, ErrorMessage = "InterfaceType is only allowed for ASCII code characters.")]
        public string InterfaceType { get; set; }
    
        [StringLength(30, ErrorMessage = "SerialNumber length should be less than 30 symbols.")]
        [RegularExpression(Utility.Const.AsciiCodeCharactersReg, ErrorMessage = "SerialNumber is only allowed for ASCII code characters.")]
        public string SerialNumber { get; set; }
    
        [StringLength(64, ErrorMessage = "MessageId length should be less than 64 symbols.")]
        [RegularExpression(Utility.Const.AsciiCodeCharactersReg, ErrorMessage = "MessageId is only allowed for ASCII code characters.")]
        public string MessageId { get; set; }
    
        [Required(ErrorMessage = "CreateDatetime is required.")]
        public System.DateTime CreateDatetime { get; set; }
    
    }
}
