//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Core.DBAccessor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    
    /// <summary>
    /// DtDxaQcLogクラス
    /// </summary>
    [ModelMetadataType(typeof(DtDxaQcLogModelMetaData))]
    public partial class DtDxaQcLog
    {
        /// <summary>
        /// コンストラクタ
        /// </summary>
        public DtDxaQcLog()
        {
        }
    
        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <param name="model">Utility.Models.Entites.DtDxaQcLogのインスタンス</param>
        public DtDxaQcLog(Utility.Models.Entites.DtDxaQcLog model)
        {
            this.Sid = model.Sid;
            this.DeviceSid = model.DeviceSid;
            this.SourceEquipmentUid = model.SourceEquipmentUid;
            this.StudyInstanceUid = model.StudyInstanceUid;
            this.SopInstanceUid = model.SopInstanceUid;
            this.StudyDatetime = model.StudyDatetime;
            this.MeasureDatetime = model.MeasureDatetime;
            this.PanelSerialId = model.PanelSerialId;
            this.TechniqueCode = model.TechniqueCode;
            this.TypeName = model.TypeName;
            this.QcResult = model.QcResult;
            this.BmcDxaATest = model.BmcDxaATest;
            this.BmcDxaBTest = model.BmcDxaBTest;
            this.BmcDxaCTest = model.BmcDxaCTest;
            this.AreaDxaATest = model.AreaDxaATest;
            this.AreaDxaBTest = model.AreaDxaBTest;
            this.AreaDxaCTest = model.AreaDxaCTest;
            this.BmdDxaATest = model.BmdDxaATest;
            this.BmdDxaBTest = model.BmdDxaBTest;
            this.BmdDxaCTest = model.BmdDxaCTest;
            this.BmdLinearityTest = model.BmdLinearityTest;
            this.QlCsiBoneATest = model.QlCsiBoneATest;
            this.QlCsiBoneBTest = model.QlCsiBoneBTest;
            this.QlCsiBoneCTest = model.QlCsiBoneCTest;
            this.QlCsiSoftLaTest = model.QlCsiSoftLaTest;
            this.QlCsiSoftLbTest = model.QlCsiSoftLbTest;
            this.QlCsiSoftLcTest = model.QlCsiSoftLcTest;
            this.QlCsiSoftRaTest = model.QlCsiSoftRaTest;
            this.QlCsiSoftRbTest = model.QlCsiSoftRbTest;
            this.QlCsiSoftRcTest = model.QlCsiSoftRcTest;
            this.QlGosBoneATest = model.QlGosBoneATest;
            this.QlGosBoneBTest = model.QlGosBoneBTest;
            this.QlGosBoneCTest = model.QlGosBoneCTest;
            this.QlGosSoftLaTest = model.QlGosSoftLaTest;
            this.QlGosSoftLbTest = model.QlGosSoftLbTest;
            this.QlGosSoftLcTest = model.QlGosSoftLcTest;
            this.QlGosSoftRaTest = model.QlGosSoftRaTest;
            this.QlGosSoftRbTest = model.QlGosSoftRbTest;
            this.QlGosSoftRcTest = model.QlGosSoftRcTest;
            this.QlDxaBoneATest = model.QlDxaBoneATest;
            this.QlDxaBoneBTest = model.QlDxaBoneBTest;
            this.QlDxaBoneCTest = model.QlDxaBoneCTest;
            this.QlDxaSoftLaTest = model.QlDxaSoftLaTest;
            this.QlDxaSoftLbTest = model.QlDxaSoftLbTest;
            this.QlDxaSoftLcTest = model.QlDxaSoftLcTest;
            this.QlDxaSoftRaTest = model.QlDxaSoftRaTest;
            this.QlDxaSoftRbTest = model.QlDxaSoftRbTest;
            this.QlDxaSoftRcTest = model.QlDxaSoftRcTest;
            this.StdCsiBoneATest = model.StdCsiBoneATest;
            this.StdCsiBoneBTest = model.StdCsiBoneBTest;
            this.StdCsiBoneCTest = model.StdCsiBoneCTest;
            this.StdCsiSoftLaTest = model.StdCsiSoftLaTest;
            this.StdCsiSoftLbTest = model.StdCsiSoftLbTest;
            this.StdCsiSoftLcTest = model.StdCsiSoftLcTest;
            this.StdCsiSoftRaTest = model.StdCsiSoftRaTest;
            this.StdCsiSoftRbTest = model.StdCsiSoftRbTest;
            this.StdCsiSoftRcTest = model.StdCsiSoftRcTest;
            this.StdGosBoneATest = model.StdGosBoneATest;
            this.StdGosBoneBTest = model.StdGosBoneBTest;
            this.StdGosBoneCTest = model.StdGosBoneCTest;
            this.StdGosSoftLaTest = model.StdGosSoftLaTest;
            this.StdGosSoftLbTest = model.StdGosSoftLbTest;
            this.StdGosSoftLcTest = model.StdGosSoftLcTest;
            this.StdGosSoftRaTest = model.StdGosSoftRaTest;
            this.StdGosSoftRbTest = model.StdGosSoftRbTest;
            this.StdGosSoftRcTest = model.StdGosSoftRcTest;
            this.StdDxaBoneATest = model.StdDxaBoneATest;
            this.StdDxaBoneBTest = model.StdDxaBoneBTest;
            this.StdDxaBoneCTest = model.StdDxaBoneCTest;
            this.StdDxaSoftLaTest = model.StdDxaSoftLaTest;
            this.StdDxaSoftLbTest = model.StdDxaSoftLbTest;
            this.StdDxaSoftLcTest = model.StdDxaSoftLcTest;
            this.StdDxaSoftRaTest = model.StdDxaSoftRaTest;
            this.StdDxaSoftRbTest = model.StdDxaSoftRbTest;
            this.StdDxaSoftRcTest = model.StdDxaSoftRcTest;
            this.BmdDxaABasvalTest = model.BmdDxaABasvalTest;
            this.BmdDxaBBasvalTest = model.BmdDxaBBasvalTest;
            this.BmdDxaCBasvalTest = model.BmdDxaCBasvalTest;
            this.QlCsiBoneABasvalTest = model.QlCsiBoneABasvalTest;
            this.QlCsiBoneBBasvalTest = model.QlCsiBoneBBasvalTest;
            this.QlCsiBoneCBasvalTest = model.QlCsiBoneCBasvalTest;
            this.QlCsiSoftLaBasvalTest = model.QlCsiSoftLaBasvalTest;
            this.QlCsiSoftLbBasvalTest = model.QlCsiSoftLbBasvalTest;
            this.QlCsiSoftLcBasvalTest = model.QlCsiSoftLcBasvalTest;
            this.QlCsiSoftRaBasvalTest = model.QlCsiSoftRaBasvalTest;
            this.QlCsiSoftRbBasvalTest = model.QlCsiSoftRbBasvalTest;
            this.QlCsiSoftRcBasvalTest = model.QlCsiSoftRcBasvalTest;
            this.QlGosBoneABasvalTest = model.QlGosBoneABasvalTest;
            this.QlGosBoneBBasvalTest = model.QlGosBoneBBasvalTest;
            this.QlGosBoneCBasvalTest = model.QlGosBoneCBasvalTest;
            this.QlGosSoftLaBasvalTest = model.QlGosSoftLaBasvalTest;
            this.QlGosSoftLbBasvalTest = model.QlGosSoftLbBasvalTest;
            this.QlGosSoftLcBasvalTest = model.QlGosSoftLcBasvalTest;
            this.QlGosSoftRaBasvalTest = model.QlGosSoftRaBasvalTest;
            this.QlGosSoftRbBasvalTest = model.QlGosSoftRbBasvalTest;
            this.QlGosSoftRcBasvalTest = model.QlGosSoftRcBasvalTest;
            this.QlDxaBoneABasvalTest = model.QlDxaBoneABasvalTest;
            this.QlDxaBoneBBasvalTest = model.QlDxaBoneBBasvalTest;
            this.QlDxaBoneCBasvalTest = model.QlDxaBoneCBasvalTest;
            this.QlDxaSoftLaBasvalTest = model.QlDxaSoftLaBasvalTest;
            this.QlDxaSoftLbBasvalTest = model.QlDxaSoftLbBasvalTest;
            this.QlDxaSoftLcBasvalTest = model.QlDxaSoftLcBasvalTest;
            this.QlDxaSoftRaBasvalTest = model.QlDxaSoftRaBasvalTest;
            this.QlDxaSoftRbBasvalTest = model.QlDxaSoftRbBasvalTest;
            this.QlDxaSoftRcBasvalTest = model.QlDxaSoftRcBasvalTest;
            this.StdCsiBoneABasvalTest = model.StdCsiBoneABasvalTest;
            this.StdCsiBoneBBasvalTest = model.StdCsiBoneBBasvalTest;
            this.StdCsiBoneCBasvalTest = model.StdCsiBoneCBasvalTest;
            this.StdCsiSoftLaBasvalTest = model.StdCsiSoftLaBasvalTest;
            this.StdCsiSoftLbBasvalTest = model.StdCsiSoftLbBasvalTest;
            this.StdCsiSoftLcBasvalTest = model.StdCsiSoftLcBasvalTest;
            this.StdCsiSoftRaBasvalTest = model.StdCsiSoftRaBasvalTest;
            this.StdCsiSoftRbBasvalTest = model.StdCsiSoftRbBasvalTest;
            this.StdCsiSoftRcBasvalTest = model.StdCsiSoftRcBasvalTest;
            this.StdGosBoneABasvalTest = model.StdGosBoneABasvalTest;
            this.StdGosBoneBBasvalTest = model.StdGosBoneBBasvalTest;
            this.StdGosBoneCBasvalTest = model.StdGosBoneCBasvalTest;
            this.StdGosSoftLaBasvalTest = model.StdGosSoftLaBasvalTest;
            this.StdGosSoftLbBasvalTest = model.StdGosSoftLbBasvalTest;
            this.StdGosSoftLcBasvalTest = model.StdGosSoftLcBasvalTest;
            this.StdGosSoftRaBasvalTest = model.StdGosSoftRaBasvalTest;
            this.StdGosSoftRbBasvalTest = model.StdGosSoftRbBasvalTest;
            this.StdGosSoftRcBasvalTest = model.StdGosSoftRcBasvalTest;
            this.StdDxaBoneABasvalTest = model.StdDxaBoneABasvalTest;
            this.StdDxaBoneBBasvalTest = model.StdDxaBoneBBasvalTest;
            this.StdDxaBoneCBasvalTest = model.StdDxaBoneCBasvalTest;
            this.StdDxaSoftLaBasvalTest = model.StdDxaSoftLaBasvalTest;
            this.StdDxaSoftLbBasvalTest = model.StdDxaSoftLbBasvalTest;
            this.StdDxaSoftLcBasvalTest = model.StdDxaSoftLcBasvalTest;
            this.StdDxaSoftRaBasvalTest = model.StdDxaSoftRaBasvalTest;
            this.StdDxaSoftRbBasvalTest = model.StdDxaSoftRbBasvalTest;
            this.StdDxaSoftRcBasvalTest = model.StdDxaSoftRcBasvalTest;
            this.CollectDatetime = model.CollectDatetime;
            this.MessageId = model.MessageId;
            this.CreateDatetime = model.CreateDatetime;
            this.DeviceS = model.DtDevice == null ?
                null :
                new DtDevice(model.DtDevice);
        }
    
        /// <summary>
        /// このインスタンスの各プロパティに、引数に指定されたDtDxaQcLogのプロパティの値をコピーする
        /// </summary>
        /// <param name="entity">コピー元のDtDxaQcLog</param>
        public void CopyFrom(DtDxaQcLog entity)
        {
            this.Sid = entity.Sid;
            this.DeviceSid = entity.DeviceSid;
            this.SourceEquipmentUid = entity.SourceEquipmentUid;
            this.StudyInstanceUid = entity.StudyInstanceUid;
            this.SopInstanceUid = entity.SopInstanceUid;
            this.StudyDatetime = entity.StudyDatetime;
            this.MeasureDatetime = entity.MeasureDatetime;
            this.PanelSerialId = entity.PanelSerialId;
            this.TechniqueCode = entity.TechniqueCode;
            this.TypeName = entity.TypeName;
            this.QcResult = entity.QcResult;
            this.BmcDxaATest = entity.BmcDxaATest;
            this.BmcDxaBTest = entity.BmcDxaBTest;
            this.BmcDxaCTest = entity.BmcDxaCTest;
            this.AreaDxaATest = entity.AreaDxaATest;
            this.AreaDxaBTest = entity.AreaDxaBTest;
            this.AreaDxaCTest = entity.AreaDxaCTest;
            this.BmdDxaATest = entity.BmdDxaATest;
            this.BmdDxaBTest = entity.BmdDxaBTest;
            this.BmdDxaCTest = entity.BmdDxaCTest;
            this.BmdLinearityTest = entity.BmdLinearityTest;
            this.QlCsiBoneATest = entity.QlCsiBoneATest;
            this.QlCsiBoneBTest = entity.QlCsiBoneBTest;
            this.QlCsiBoneCTest = entity.QlCsiBoneCTest;
            this.QlCsiSoftLaTest = entity.QlCsiSoftLaTest;
            this.QlCsiSoftLbTest = entity.QlCsiSoftLbTest;
            this.QlCsiSoftLcTest = entity.QlCsiSoftLcTest;
            this.QlCsiSoftRaTest = entity.QlCsiSoftRaTest;
            this.QlCsiSoftRbTest = entity.QlCsiSoftRbTest;
            this.QlCsiSoftRcTest = entity.QlCsiSoftRcTest;
            this.QlGosBoneATest = entity.QlGosBoneATest;
            this.QlGosBoneBTest = entity.QlGosBoneBTest;
            this.QlGosBoneCTest = entity.QlGosBoneCTest;
            this.QlGosSoftLaTest = entity.QlGosSoftLaTest;
            this.QlGosSoftLbTest = entity.QlGosSoftLbTest;
            this.QlGosSoftLcTest = entity.QlGosSoftLcTest;
            this.QlGosSoftRaTest = entity.QlGosSoftRaTest;
            this.QlGosSoftRbTest = entity.QlGosSoftRbTest;
            this.QlGosSoftRcTest = entity.QlGosSoftRcTest;
            this.QlDxaBoneATest = entity.QlDxaBoneATest;
            this.QlDxaBoneBTest = entity.QlDxaBoneBTest;
            this.QlDxaBoneCTest = entity.QlDxaBoneCTest;
            this.QlDxaSoftLaTest = entity.QlDxaSoftLaTest;
            this.QlDxaSoftLbTest = entity.QlDxaSoftLbTest;
            this.QlDxaSoftLcTest = entity.QlDxaSoftLcTest;
            this.QlDxaSoftRaTest = entity.QlDxaSoftRaTest;
            this.QlDxaSoftRbTest = entity.QlDxaSoftRbTest;
            this.QlDxaSoftRcTest = entity.QlDxaSoftRcTest;
            this.StdCsiBoneATest = entity.StdCsiBoneATest;
            this.StdCsiBoneBTest = entity.StdCsiBoneBTest;
            this.StdCsiBoneCTest = entity.StdCsiBoneCTest;
            this.StdCsiSoftLaTest = entity.StdCsiSoftLaTest;
            this.StdCsiSoftLbTest = entity.StdCsiSoftLbTest;
            this.StdCsiSoftLcTest = entity.StdCsiSoftLcTest;
            this.StdCsiSoftRaTest = entity.StdCsiSoftRaTest;
            this.StdCsiSoftRbTest = entity.StdCsiSoftRbTest;
            this.StdCsiSoftRcTest = entity.StdCsiSoftRcTest;
            this.StdGosBoneATest = entity.StdGosBoneATest;
            this.StdGosBoneBTest = entity.StdGosBoneBTest;
            this.StdGosBoneCTest = entity.StdGosBoneCTest;
            this.StdGosSoftLaTest = entity.StdGosSoftLaTest;
            this.StdGosSoftLbTest = entity.StdGosSoftLbTest;
            this.StdGosSoftLcTest = entity.StdGosSoftLcTest;
            this.StdGosSoftRaTest = entity.StdGosSoftRaTest;
            this.StdGosSoftRbTest = entity.StdGosSoftRbTest;
            this.StdGosSoftRcTest = entity.StdGosSoftRcTest;
            this.StdDxaBoneATest = entity.StdDxaBoneATest;
            this.StdDxaBoneBTest = entity.StdDxaBoneBTest;
            this.StdDxaBoneCTest = entity.StdDxaBoneCTest;
            this.StdDxaSoftLaTest = entity.StdDxaSoftLaTest;
            this.StdDxaSoftLbTest = entity.StdDxaSoftLbTest;
            this.StdDxaSoftLcTest = entity.StdDxaSoftLcTest;
            this.StdDxaSoftRaTest = entity.StdDxaSoftRaTest;
            this.StdDxaSoftRbTest = entity.StdDxaSoftRbTest;
            this.StdDxaSoftRcTest = entity.StdDxaSoftRcTest;
            this.BmdDxaABasvalTest = entity.BmdDxaABasvalTest;
            this.BmdDxaBBasvalTest = entity.BmdDxaBBasvalTest;
            this.BmdDxaCBasvalTest = entity.BmdDxaCBasvalTest;
            this.QlCsiBoneABasvalTest = entity.QlCsiBoneABasvalTest;
            this.QlCsiBoneBBasvalTest = entity.QlCsiBoneBBasvalTest;
            this.QlCsiBoneCBasvalTest = entity.QlCsiBoneCBasvalTest;
            this.QlCsiSoftLaBasvalTest = entity.QlCsiSoftLaBasvalTest;
            this.QlCsiSoftLbBasvalTest = entity.QlCsiSoftLbBasvalTest;
            this.QlCsiSoftLcBasvalTest = entity.QlCsiSoftLcBasvalTest;
            this.QlCsiSoftRaBasvalTest = entity.QlCsiSoftRaBasvalTest;
            this.QlCsiSoftRbBasvalTest = entity.QlCsiSoftRbBasvalTest;
            this.QlCsiSoftRcBasvalTest = entity.QlCsiSoftRcBasvalTest;
            this.QlGosBoneABasvalTest = entity.QlGosBoneABasvalTest;
            this.QlGosBoneBBasvalTest = entity.QlGosBoneBBasvalTest;
            this.QlGosBoneCBasvalTest = entity.QlGosBoneCBasvalTest;
            this.QlGosSoftLaBasvalTest = entity.QlGosSoftLaBasvalTest;
            this.QlGosSoftLbBasvalTest = entity.QlGosSoftLbBasvalTest;
            this.QlGosSoftLcBasvalTest = entity.QlGosSoftLcBasvalTest;
            this.QlGosSoftRaBasvalTest = entity.QlGosSoftRaBasvalTest;
            this.QlGosSoftRbBasvalTest = entity.QlGosSoftRbBasvalTest;
            this.QlGosSoftRcBasvalTest = entity.QlGosSoftRcBasvalTest;
            this.QlDxaBoneABasvalTest = entity.QlDxaBoneABasvalTest;
            this.QlDxaBoneBBasvalTest = entity.QlDxaBoneBBasvalTest;
            this.QlDxaBoneCBasvalTest = entity.QlDxaBoneCBasvalTest;
            this.QlDxaSoftLaBasvalTest = entity.QlDxaSoftLaBasvalTest;
            this.QlDxaSoftLbBasvalTest = entity.QlDxaSoftLbBasvalTest;
            this.QlDxaSoftLcBasvalTest = entity.QlDxaSoftLcBasvalTest;
            this.QlDxaSoftRaBasvalTest = entity.QlDxaSoftRaBasvalTest;
            this.QlDxaSoftRbBasvalTest = entity.QlDxaSoftRbBasvalTest;
            this.QlDxaSoftRcBasvalTest = entity.QlDxaSoftRcBasvalTest;
            this.StdCsiBoneABasvalTest = entity.StdCsiBoneABasvalTest;
            this.StdCsiBoneBBasvalTest = entity.StdCsiBoneBBasvalTest;
            this.StdCsiBoneCBasvalTest = entity.StdCsiBoneCBasvalTest;
            this.StdCsiSoftLaBasvalTest = entity.StdCsiSoftLaBasvalTest;
            this.StdCsiSoftLbBasvalTest = entity.StdCsiSoftLbBasvalTest;
            this.StdCsiSoftLcBasvalTest = entity.StdCsiSoftLcBasvalTest;
            this.StdCsiSoftRaBasvalTest = entity.StdCsiSoftRaBasvalTest;
            this.StdCsiSoftRbBasvalTest = entity.StdCsiSoftRbBasvalTest;
            this.StdCsiSoftRcBasvalTest = entity.StdCsiSoftRcBasvalTest;
            this.StdGosBoneABasvalTest = entity.StdGosBoneABasvalTest;
            this.StdGosBoneBBasvalTest = entity.StdGosBoneBBasvalTest;
            this.StdGosBoneCBasvalTest = entity.StdGosBoneCBasvalTest;
            this.StdGosSoftLaBasvalTest = entity.StdGosSoftLaBasvalTest;
            this.StdGosSoftLbBasvalTest = entity.StdGosSoftLbBasvalTest;
            this.StdGosSoftLcBasvalTest = entity.StdGosSoftLcBasvalTest;
            this.StdGosSoftRaBasvalTest = entity.StdGosSoftRaBasvalTest;
            this.StdGosSoftRbBasvalTest = entity.StdGosSoftRbBasvalTest;
            this.StdGosSoftRcBasvalTest = entity.StdGosSoftRcBasvalTest;
            this.StdDxaBoneABasvalTest = entity.StdDxaBoneABasvalTest;
            this.StdDxaBoneBBasvalTest = entity.StdDxaBoneBBasvalTest;
            this.StdDxaBoneCBasvalTest = entity.StdDxaBoneCBasvalTest;
            this.StdDxaSoftLaBasvalTest = entity.StdDxaSoftLaBasvalTest;
            this.StdDxaSoftLbBasvalTest = entity.StdDxaSoftLbBasvalTest;
            this.StdDxaSoftLcBasvalTest = entity.StdDxaSoftLcBasvalTest;
            this.StdDxaSoftRaBasvalTest = entity.StdDxaSoftRaBasvalTest;
            this.StdDxaSoftRbBasvalTest = entity.StdDxaSoftRbBasvalTest;
            this.StdDxaSoftRcBasvalTest = entity.StdDxaSoftRcBasvalTest;
            this.CollectDatetime = entity.CollectDatetime;
            this.MessageId = entity.MessageId;
            this.CreateDatetime = entity.CreateDatetime;
            this.DeviceS = entity.DeviceS;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.DtDxaQcLog型に変換する。
        /// 各変換メソッド共通部分
        /// </summary>
        /// <returns></returns>
        private Utility.Models.Entites.DtDxaQcLog ToModelCommonPart()
        {
            Utility.Models.Entites.DtDxaQcLog model = new Utility.Models.Entites.DtDxaQcLog();
            model.Sid = this.Sid;
            model.DeviceSid = this.DeviceSid;
            model.SourceEquipmentUid = this.SourceEquipmentUid;
            model.StudyInstanceUid = this.StudyInstanceUid;
            model.SopInstanceUid = this.SopInstanceUid;
            model.StudyDatetime = this.StudyDatetime;
            model.MeasureDatetime = this.MeasureDatetime;
            model.PanelSerialId = this.PanelSerialId;
            model.TechniqueCode = this.TechniqueCode;
            model.TypeName = this.TypeName;
            model.QcResult = this.QcResult;
            model.BmcDxaATest = this.BmcDxaATest;
            model.BmcDxaBTest = this.BmcDxaBTest;
            model.BmcDxaCTest = this.BmcDxaCTest;
            model.AreaDxaATest = this.AreaDxaATest;
            model.AreaDxaBTest = this.AreaDxaBTest;
            model.AreaDxaCTest = this.AreaDxaCTest;
            model.BmdDxaATest = this.BmdDxaATest;
            model.BmdDxaBTest = this.BmdDxaBTest;
            model.BmdDxaCTest = this.BmdDxaCTest;
            model.BmdLinearityTest = this.BmdLinearityTest;
            model.QlCsiBoneATest = this.QlCsiBoneATest;
            model.QlCsiBoneBTest = this.QlCsiBoneBTest;
            model.QlCsiBoneCTest = this.QlCsiBoneCTest;
            model.QlCsiSoftLaTest = this.QlCsiSoftLaTest;
            model.QlCsiSoftLbTest = this.QlCsiSoftLbTest;
            model.QlCsiSoftLcTest = this.QlCsiSoftLcTest;
            model.QlCsiSoftRaTest = this.QlCsiSoftRaTest;
            model.QlCsiSoftRbTest = this.QlCsiSoftRbTest;
            model.QlCsiSoftRcTest = this.QlCsiSoftRcTest;
            model.QlGosBoneATest = this.QlGosBoneATest;
            model.QlGosBoneBTest = this.QlGosBoneBTest;
            model.QlGosBoneCTest = this.QlGosBoneCTest;
            model.QlGosSoftLaTest = this.QlGosSoftLaTest;
            model.QlGosSoftLbTest = this.QlGosSoftLbTest;
            model.QlGosSoftLcTest = this.QlGosSoftLcTest;
            model.QlGosSoftRaTest = this.QlGosSoftRaTest;
            model.QlGosSoftRbTest = this.QlGosSoftRbTest;
            model.QlGosSoftRcTest = this.QlGosSoftRcTest;
            model.QlDxaBoneATest = this.QlDxaBoneATest;
            model.QlDxaBoneBTest = this.QlDxaBoneBTest;
            model.QlDxaBoneCTest = this.QlDxaBoneCTest;
            model.QlDxaSoftLaTest = this.QlDxaSoftLaTest;
            model.QlDxaSoftLbTest = this.QlDxaSoftLbTest;
            model.QlDxaSoftLcTest = this.QlDxaSoftLcTest;
            model.QlDxaSoftRaTest = this.QlDxaSoftRaTest;
            model.QlDxaSoftRbTest = this.QlDxaSoftRbTest;
            model.QlDxaSoftRcTest = this.QlDxaSoftRcTest;
            model.StdCsiBoneATest = this.StdCsiBoneATest;
            model.StdCsiBoneBTest = this.StdCsiBoneBTest;
            model.StdCsiBoneCTest = this.StdCsiBoneCTest;
            model.StdCsiSoftLaTest = this.StdCsiSoftLaTest;
            model.StdCsiSoftLbTest = this.StdCsiSoftLbTest;
            model.StdCsiSoftLcTest = this.StdCsiSoftLcTest;
            model.StdCsiSoftRaTest = this.StdCsiSoftRaTest;
            model.StdCsiSoftRbTest = this.StdCsiSoftRbTest;
            model.StdCsiSoftRcTest = this.StdCsiSoftRcTest;
            model.StdGosBoneATest = this.StdGosBoneATest;
            model.StdGosBoneBTest = this.StdGosBoneBTest;
            model.StdGosBoneCTest = this.StdGosBoneCTest;
            model.StdGosSoftLaTest = this.StdGosSoftLaTest;
            model.StdGosSoftLbTest = this.StdGosSoftLbTest;
            model.StdGosSoftLcTest = this.StdGosSoftLcTest;
            model.StdGosSoftRaTest = this.StdGosSoftRaTest;
            model.StdGosSoftRbTest = this.StdGosSoftRbTest;
            model.StdGosSoftRcTest = this.StdGosSoftRcTest;
            model.StdDxaBoneATest = this.StdDxaBoneATest;
            model.StdDxaBoneBTest = this.StdDxaBoneBTest;
            model.StdDxaBoneCTest = this.StdDxaBoneCTest;
            model.StdDxaSoftLaTest = this.StdDxaSoftLaTest;
            model.StdDxaSoftLbTest = this.StdDxaSoftLbTest;
            model.StdDxaSoftLcTest = this.StdDxaSoftLcTest;
            model.StdDxaSoftRaTest = this.StdDxaSoftRaTest;
            model.StdDxaSoftRbTest = this.StdDxaSoftRbTest;
            model.StdDxaSoftRcTest = this.StdDxaSoftRcTest;
            model.BmdDxaABasvalTest = this.BmdDxaABasvalTest;
            model.BmdDxaBBasvalTest = this.BmdDxaBBasvalTest;
            model.BmdDxaCBasvalTest = this.BmdDxaCBasvalTest;
            model.QlCsiBoneABasvalTest = this.QlCsiBoneABasvalTest;
            model.QlCsiBoneBBasvalTest = this.QlCsiBoneBBasvalTest;
            model.QlCsiBoneCBasvalTest = this.QlCsiBoneCBasvalTest;
            model.QlCsiSoftLaBasvalTest = this.QlCsiSoftLaBasvalTest;
            model.QlCsiSoftLbBasvalTest = this.QlCsiSoftLbBasvalTest;
            model.QlCsiSoftLcBasvalTest = this.QlCsiSoftLcBasvalTest;
            model.QlCsiSoftRaBasvalTest = this.QlCsiSoftRaBasvalTest;
            model.QlCsiSoftRbBasvalTest = this.QlCsiSoftRbBasvalTest;
            model.QlCsiSoftRcBasvalTest = this.QlCsiSoftRcBasvalTest;
            model.QlGosBoneABasvalTest = this.QlGosBoneABasvalTest;
            model.QlGosBoneBBasvalTest = this.QlGosBoneBBasvalTest;
            model.QlGosBoneCBasvalTest = this.QlGosBoneCBasvalTest;
            model.QlGosSoftLaBasvalTest = this.QlGosSoftLaBasvalTest;
            model.QlGosSoftLbBasvalTest = this.QlGosSoftLbBasvalTest;
            model.QlGosSoftLcBasvalTest = this.QlGosSoftLcBasvalTest;
            model.QlGosSoftRaBasvalTest = this.QlGosSoftRaBasvalTest;
            model.QlGosSoftRbBasvalTest = this.QlGosSoftRbBasvalTest;
            model.QlGosSoftRcBasvalTest = this.QlGosSoftRcBasvalTest;
            model.QlDxaBoneABasvalTest = this.QlDxaBoneABasvalTest;
            model.QlDxaBoneBBasvalTest = this.QlDxaBoneBBasvalTest;
            model.QlDxaBoneCBasvalTest = this.QlDxaBoneCBasvalTest;
            model.QlDxaSoftLaBasvalTest = this.QlDxaSoftLaBasvalTest;
            model.QlDxaSoftLbBasvalTest = this.QlDxaSoftLbBasvalTest;
            model.QlDxaSoftLcBasvalTest = this.QlDxaSoftLcBasvalTest;
            model.QlDxaSoftRaBasvalTest = this.QlDxaSoftRaBasvalTest;
            model.QlDxaSoftRbBasvalTest = this.QlDxaSoftRbBasvalTest;
            model.QlDxaSoftRcBasvalTest = this.QlDxaSoftRcBasvalTest;
            model.StdCsiBoneABasvalTest = this.StdCsiBoneABasvalTest;
            model.StdCsiBoneBBasvalTest = this.StdCsiBoneBBasvalTest;
            model.StdCsiBoneCBasvalTest = this.StdCsiBoneCBasvalTest;
            model.StdCsiSoftLaBasvalTest = this.StdCsiSoftLaBasvalTest;
            model.StdCsiSoftLbBasvalTest = this.StdCsiSoftLbBasvalTest;
            model.StdCsiSoftLcBasvalTest = this.StdCsiSoftLcBasvalTest;
            model.StdCsiSoftRaBasvalTest = this.StdCsiSoftRaBasvalTest;
            model.StdCsiSoftRbBasvalTest = this.StdCsiSoftRbBasvalTest;
            model.StdCsiSoftRcBasvalTest = this.StdCsiSoftRcBasvalTest;
            model.StdGosBoneABasvalTest = this.StdGosBoneABasvalTest;
            model.StdGosBoneBBasvalTest = this.StdGosBoneBBasvalTest;
            model.StdGosBoneCBasvalTest = this.StdGosBoneCBasvalTest;
            model.StdGosSoftLaBasvalTest = this.StdGosSoftLaBasvalTest;
            model.StdGosSoftLbBasvalTest = this.StdGosSoftLbBasvalTest;
            model.StdGosSoftLcBasvalTest = this.StdGosSoftLcBasvalTest;
            model.StdGosSoftRaBasvalTest = this.StdGosSoftRaBasvalTest;
            model.StdGosSoftRbBasvalTest = this.StdGosSoftRbBasvalTest;
            model.StdGosSoftRcBasvalTest = this.StdGosSoftRcBasvalTest;
            model.StdDxaBoneABasvalTest = this.StdDxaBoneABasvalTest;
            model.StdDxaBoneBBasvalTest = this.StdDxaBoneBBasvalTest;
            model.StdDxaBoneCBasvalTest = this.StdDxaBoneCBasvalTest;
            model.StdDxaSoftLaBasvalTest = this.StdDxaSoftLaBasvalTest;
            model.StdDxaSoftLbBasvalTest = this.StdDxaSoftLbBasvalTest;
            model.StdDxaSoftLcBasvalTest = this.StdDxaSoftLcBasvalTest;
            model.StdDxaSoftRaBasvalTest = this.StdDxaSoftRaBasvalTest;
            model.StdDxaSoftRbBasvalTest = this.StdDxaSoftRbBasvalTest;
            model.StdDxaSoftRcBasvalTest = this.StdDxaSoftRcBasvalTest;
            model.CollectDatetime = this.CollectDatetime;
            model.MessageId = this.MessageId;
            model.CreateDatetime = this.CreateDatetime;
            return model;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.DtDxaQcLog型に変換する。
        /// </summary>
        /// <returns></returns>
        public Utility.Models.Entites.DtDxaQcLog ToModel()
        {
            Utility.Models.Entites.DtDxaQcLog model = ToModelCommonPart();
            model.DtDevice = this.DeviceS?.ToParentModel(this.GetType());
    
            return model;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.DtDxaQcLog型に変換する。
        /// 親エンティティとして生成するため、子エンティティの情報はもたない
        /// </summary>
        /// <returns></returns>
        public Utility.Models.Entites.DtDxaQcLog ToParentModel(Type childType)
        {
            Utility.Models.Entites.DtDxaQcLog model = ToModelCommonPart();
            model.DtDevice = this.DeviceS?.ToParentModel(this.GetType());
    
            return model;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.DtDxaQcLog型に変換する。
        /// 子エンティティとして生成するため、親エンティティの情報をもたない
        /// </summary>
        /// <returns></returns>
        public Utility.Models.Entites.DtDxaQcLog ToChildModel(Type parentType)
        {
            Utility.Models.Entites.DtDxaQcLog model = ToModelCommonPart();
            // 親子間の参照無限ループを避けるためにタイプチェック
            if (this.DeviceS?.GetType() != parentType)
            {
                model.DtDevice = this.DeviceS?.ToParentModel(this.GetType());
            }
    
            return model;
        }
    }
    
    /// <summary>
    /// DtDxaQcLogのメタデータクラス
    /// </summary>
    public  class DtDxaQcLogModelMetaData
    {
        [Key]
        [Required(ErrorMessage = "Sid is required.")]
        public long Sid { get; set; }
    
        [Required(ErrorMessage = "DeviceSid is required.")]
        public long DeviceSid { get; set; }
    
        [StringLength(30, ErrorMessage = "SourceEquipmentUid length should be less than 30 symbols.")]
        [RegularExpression(Utility.Const.AsciiCodeCharactersReg, ErrorMessage = "SourceEquipmentUid is only allowed for ASCII code characters.")]
        public string SourceEquipmentUid { get; set; }
    
        [StringLength(128, ErrorMessage = "StudyInstanceUid length should be less than 128 symbols.")]
        [RegularExpression(Utility.Const.AsciiCodeCharactersReg, ErrorMessage = "StudyInstanceUid is only allowed for ASCII code characters.")]
        public string StudyInstanceUid { get; set; }
    
        [StringLength(128, ErrorMessage = "SopInstanceUid length should be less than 128 symbols.")]
        [RegularExpression(Utility.Const.AsciiCodeCharactersReg, ErrorMessage = "SopInstanceUid is only allowed for ASCII code characters.")]
        public string SopInstanceUid { get; set; }
    
        [StringLength(30, ErrorMessage = "PanelSerialId length should be less than 30 symbols.")]
        [RegularExpression(Utility.Const.AsciiCodeCharactersReg, ErrorMessage = "PanelSerialId is only allowed for ASCII code characters.")]
        public string PanelSerialId { get; set; }
    
        [StringLength(64, ErrorMessage = "MessageId length should be less than 64 symbols.")]
        [RegularExpression(Utility.Const.AsciiCodeCharactersReg, ErrorMessage = "MessageId is only allowed for ASCII code characters.")]
        public string MessageId { get; set; }
    
        [Required(ErrorMessage = "CreateDatetime is required.")]
        public System.DateTime CreateDatetime { get; set; }
    
    }
}
