//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Core.DBAccessor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    
    /// <summary>
    /// DtSoftVersionクラス
    /// </summary>
    [ModelMetadataType(typeof(DtSoftVersionModelMetaData))]
    public partial class DtSoftVersion
    {
        /// <summary>
        /// コンストラクタ
        /// </summary>
        public DtSoftVersion()
        {
        }
    
        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <param name="model">Utility.Models.Entites.DtSoftVersionのインスタンス</param>
        public DtSoftVersion(Utility.Models.Entites.DtSoftVersion model)
        {
            this.Sid = model.Sid;
            this.DeviceSid = model.DeviceSid;
            this.EquipmentModelSid = model.EquipmentModelSid;
            this.SourceEquipmentUid = model.SourceEquipmentUid;
            this.Version = model.Version;
            this.MessageId = model.MessageId;
            this.CollectDatetime = model.CollectDatetime;
            this.CreateDatetime = model.CreateDatetime;
            this.DeviceS = model.DtDevice == null ?
                null :
                new DtDevice(model.DtDevice);
            this.EquipmentModelS = model.MtEquipmentModel == null ?
                null :
                new MtEquipmentModel(model.MtEquipmentModel);
        }
    
        /// <summary>
        /// このインスタンスの各プロパティに、引数に指定されたDtSoftVersionのプロパティの値をコピーする
        /// </summary>
        /// <param name="entity">コピー元のDtSoftVersion</param>
        public void CopyFrom(DtSoftVersion entity)
        {
            this.Sid = entity.Sid;
            this.DeviceSid = entity.DeviceSid;
            this.EquipmentModelSid = entity.EquipmentModelSid;
            this.SourceEquipmentUid = entity.SourceEquipmentUid;
            this.Version = entity.Version;
            this.MessageId = entity.MessageId;
            this.CollectDatetime = entity.CollectDatetime;
            this.CreateDatetime = entity.CreateDatetime;
            this.DeviceS = entity.DeviceS;
            this.EquipmentModelS = entity.EquipmentModelS;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.DtSoftVersion型に変換する。
        /// 各変換メソッド共通部分
        /// </summary>
        /// <returns></returns>
        private Utility.Models.Entites.DtSoftVersion ToModelCommonPart()
        {
            Utility.Models.Entites.DtSoftVersion model = new Utility.Models.Entites.DtSoftVersion();
            model.Sid = this.Sid;
            model.DeviceSid = this.DeviceSid;
            model.EquipmentModelSid = this.EquipmentModelSid;
            model.SourceEquipmentUid = this.SourceEquipmentUid;
            model.Version = this.Version;
            model.MessageId = this.MessageId;
            model.CollectDatetime = this.CollectDatetime;
            model.CreateDatetime = this.CreateDatetime;
            return model;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.DtSoftVersion型に変換する。
        /// </summary>
        /// <returns></returns>
        public Utility.Models.Entites.DtSoftVersion ToModel()
        {
            Utility.Models.Entites.DtSoftVersion model = ToModelCommonPart();
            model.DtDevice = this.DeviceS?.ToParentModel(this.GetType());
            model.MtEquipmentModel = this.EquipmentModelS?.ToParentModel(this.GetType());
    
            return model;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.DtSoftVersion型に変換する。
        /// 親エンティティとして生成するため、子エンティティの情報はもたない
        /// </summary>
        /// <returns></returns>
        public Utility.Models.Entites.DtSoftVersion ToParentModel(Type childType)
        {
            Utility.Models.Entites.DtSoftVersion model = ToModelCommonPart();
            model.DtDevice = this.DeviceS?.ToParentModel(this.GetType());
            model.MtEquipmentModel = this.EquipmentModelS?.ToParentModel(this.GetType());
    
            return model;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.DtSoftVersion型に変換する。
        /// 子エンティティとして生成するため、親エンティティの情報をもたない
        /// </summary>
        /// <returns></returns>
        public Utility.Models.Entites.DtSoftVersion ToChildModel(Type parentType)
        {
            Utility.Models.Entites.DtSoftVersion model = ToModelCommonPart();
            // 親子間の参照無限ループを避けるためにタイプチェック
            if (this.DeviceS?.GetType() != parentType)
            {
                model.DtDevice = this.DeviceS?.ToParentModel(this.GetType());
            }
            if (this.EquipmentModelS?.GetType() != parentType)
            {
                model.MtEquipmentModel = this.EquipmentModelS?.ToParentModel(this.GetType());
            }
    
            return model;
        }
    }
    
    /// <summary>
    /// DtSoftVersionのメタデータクラス
    /// </summary>
    public  class DtSoftVersionModelMetaData
    {
        [Key]
        [Required(ErrorMessage = "Sid is required.")]
        public long Sid { get; set; }
    
        [Required(ErrorMessage = "DeviceSid is required.")]
        public long DeviceSid { get; set; }
    
        [Required(ErrorMessage = "EquipmentModelSid is required.")]
        public long EquipmentModelSid { get; set; }
    
        [StringLength(30, ErrorMessage = "SourceEquipmentUid length should be less than 30 symbols.")]
        [RegularExpression(Utility.Const.AsciiCodeCharactersReg, ErrorMessage = "SourceEquipmentUid is only allowed for ASCII code characters.")]
        public string SourceEquipmentUid { get; set; }
    
        [StringLength(30, ErrorMessage = "Version length should be less than 30 symbols.")]
        [RegularExpression(Utility.Const.AsciiCodeCharactersReg, ErrorMessage = "Version is only allowed for ASCII code characters.")]
        public string Version { get; set; }
    
        [StringLength(64, ErrorMessage = "MessageId length should be less than 64 symbols.")]
        [RegularExpression(Utility.Const.AsciiCodeCharactersReg, ErrorMessage = "MessageId is only allowed for ASCII code characters.")]
        public string MessageId { get; set; }
    
        [Required(ErrorMessage = "CreateDatetime is required.")]
        public System.DateTime CreateDatetime { get; set; }
    
    }
}
