//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Core.DBAccessor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using Microsoft.AspNetCore.Mvc;
    
    /// <summary>
    /// MtEquipmentTypeクラス
    /// </summary>
    [ModelMetadataType(typeof(MtEquipmentTypeModelMetaData))]
    public partial class MtEquipmentType
    {
        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <param name="model">Utility.Models.Entites.MtEquipmentTypeのインスタンス</param>
        public MtEquipmentType(Utility.Models.Entites.MtEquipmentType model)
        {
            this.Sid = model.Sid;
            this.Code = model.Code;
            this.Description = model.Description;
            this.CreateDatetime = model.CreateDatetime;
        }
    
        /// <summary>
        /// このインスタンスの各プロパティに、引数に指定されたMtEquipmentTypeのプロパティの値をコピーする
        /// </summary>
        /// <param name="entity">コピー元のMtEquipmentType</param>
        public void CopyFrom(MtEquipmentType entity)
        {
            this.Sid = entity.Sid;
            this.Code = entity.Code;
            this.Description = entity.Description;
            this.CreateDatetime = entity.CreateDatetime;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.MtEquipmentType型に変換する。
        /// 各変換メソッド共通部分
        /// </summary>
        /// <returns></returns>
        private Utility.Models.Entites.MtEquipmentType ToModelCommonPart()
        {
            Utility.Models.Entites.MtEquipmentType model = new Utility.Models.Entites.MtEquipmentType();
            model.Sid = this.Sid;
            model.Code = this.Code;
            model.Description = this.Description;
            model.CreateDatetime = this.CreateDatetime;
            return model;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.MtEquipmentType型に変換する。
        /// </summary>
        /// <returns></returns>
        public Utility.Models.Entites.MtEquipmentType ToModel()
        {
            Utility.Models.Entites.MtEquipmentType model = ToModelCommonPart();
    
            return model;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.MtEquipmentType型に変換する。
        /// 親エンティティとして生成するため、子エンティティの情報はもたない
        /// </summary>
        /// <returns></returns>
        public Utility.Models.Entites.MtEquipmentType ToParentModel(Type childType)
        {
            Utility.Models.Entites.MtEquipmentType model = ToModelCommonPart();
            // 親子間の参照無限ループを避けるためにタイプチェック
    
            return model;
        }
    
        /// <summary>
        /// このインスタンスを、それと同等なUtility.Models.Entites.MtEquipmentType型に変換する。
        /// 子エンティティとして生成するため、親エンティティの情報をもたない
        /// </summary>
        /// <returns></returns>
        public Utility.Models.Entites.MtEquipmentType ToChildModel(Type parentType)
        {
            Utility.Models.Entites.MtEquipmentType model = ToModelCommonPart();
            // 親子間の参照無限ループを避けるためにタイプチェック
    
            return model;
        }
    }
    
    /// <summary>
    /// MtEquipmentTypeのメタデータクラス
    /// </summary>
    public  class MtEquipmentTypeModelMetaData
    {
        [Key]
        [Required(ErrorMessage = "Sid is required.")]
        public long Sid { get; set; }
    
        [Required(ErrorMessage = "Code is required.")]
        [StringLength(30, ErrorMessage = "Code length should be less than 30 symbols.")]
        [RegularExpression(Utility.Const.AsciiCodeCharactersReg, ErrorMessage = "Code is only allowed for ASCII code characters.")]
        public string Code { get; set; }
    
        [StringLength(128, ErrorMessage = "Description length should be less than 128 symbols.")]
        public string Description { get; set; }
    
        [Required(ErrorMessage = "CreateDatetime is required.")]
        public System.DateTime CreateDatetime { get; set; }
    
    }
}
