//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Utility.Utility.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rms.Server.Utility.Utility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_CLP_CLP_001 {
            get {
                return ResourceManager.GetString("UT_CLP_CLP_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（message-id: {0}）（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_CLP_CLP_002 {
            get {
                return ResourceManager.GetString("UT_CLP_CLP_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャリブレーション予兆監視アラーム定義の取得に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_CLP_CLP_003 {
            get {
                return ResourceManager.GetString("UT_CLP_CLP_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成不要。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_CLP_CLP_004 {
            get {
                return ResourceManager.GetString("UT_CLP_CLP_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_CLP_CLP_005 {
            get {
                return ResourceManager.GetString("UT_CLP_CLP_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキュー登録に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_CLP_CLP_006 {
            get {
                return ResourceManager.GetString("UT_CLP_CLP_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキューを登録しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_CLP_CLP_007 {
            get {
                return ResourceManager.GetString("UT_CLP_CLP_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再送用メッセージの保存に失敗しました。（message-id: {0}）（message: {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_CLP_CLP_008 {
            get {
                return ResourceManager.GetString("UT_CLP_CLP_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_CLP_CLP_009 {
            get {
                return ResourceManager.GetString("UT_CLP_CLP_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAA_DAA_001 {
            get {
                return ResourceManager.GetString("UT_DAA_DAA_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（message-id: {0}）（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAA_DAA_002 {
            get {
                return ResourceManager.GetString("UT_DAA_DAA_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解析結果の検索に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAA_DAA_003 {
            get {
                return ResourceManager.GetString("UT_DAA_DAA_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解析結果が既に登録済みです。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAA_DAA_004 {
            get {
                return ResourceManager.GetString("UT_DAA_DAA_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アルミスロープログの解析に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAA_DAA_005 {
            get {
                return ResourceManager.GetString("UT_DAA_DAA_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解析結果の保存に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAA_DAA_006 {
            get {
                return ResourceManager.GetString("UT_DAA_DAA_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解析結果を保存しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAA_DAA_007 {
            get {
                return ResourceManager.GetString("UT_DAA_DAA_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再送用メッセージの保存に失敗しました。（message-id: {0}）（message: {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAA_DAA_008 {
            get {
                return ResourceManager.GetString("UT_DAA_DAA_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAP_DAP_001 {
            get {
                return ResourceManager.GetString("UT_DAP_DAP_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解析結果の取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAP_DAP_002 {
            get {
                return ResourceManager.GetString("UT_DAP_DAP_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム定義の取得に失敗しました。（analysis-result-sid: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAP_DAP_003 {
            get {
                return ResourceManager.GetString("UT_DAP_DAP_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成不要。（analysis-result-sid: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAP_DAP_004 {
            get {
                return ResourceManager.GetString("UT_DAP_DAP_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成に失敗しました。（analysis-result-sid: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAP_DAP_005 {
            get {
                return ResourceManager.GetString("UT_DAP_DAP_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキュー登録に失敗しました。（analysis-result-sid: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAP_DAP_006 {
            get {
                return ResourceManager.GetString("UT_DAP_DAP_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキューを登録しました。（analysis-result-sid: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAP_DAP_007 {
            get {
                return ResourceManager.GetString("UT_DAP_DAP_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   判断実施済みフラグの更新に失敗しました。（analysis-result-sid: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAP_DAP_008 {
            get {
                return ResourceManager.GetString("UT_DAP_DAP_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   判断実施済みフラグを更新しました。（analysis-result-sid: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAP_DAP_009 {
            get {
                return ResourceManager.GetString("UT_DAP_DAP_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DAP_DAP_010 {
            get {
                return ResourceManager.GetString("UT_DAP_DAP_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DBA_DBA_001 {
            get {
                return ResourceManager.GetString("UT_DBA_DBA_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（message-id: {0}）（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DBA_DBA_002 {
            get {
                return ResourceManager.GetString("UT_DBA_DBA_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解析結果の検索に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DBA_DBA_003 {
            get {
                return ResourceManager.GetString("UT_DBA_DBA_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解析結果が既に登録済みです。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DBA_DBA_004 {
            get {
                return ResourceManager.GetString("UT_DBA_DBA_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ムラログの解析に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DBA_DBA_005 {
            get {
                return ResourceManager.GetString("UT_DBA_DBA_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解析結果の保存に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DBA_DBA_006 {
            get {
                return ResourceManager.GetString("UT_DBA_DBA_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解析結果を保存しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DBA_DBA_007 {
            get {
                return ResourceManager.GetString("UT_DBA_DBA_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再送用メッセージの保存に失敗しました。（message-id: {0}）（message: {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DBA_DBA_008 {
            get {
                return ResourceManager.GetString("UT_DBA_DBA_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DBC_DBC_001 {
            get {
                return ResourceManager.GetString("UT_DBC_DBC_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DBC_DBC_002 {
            get {
                return ResourceManager.GetString("UT_DBC_DBC_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの削除に失敗しました。（データ情報：{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DBC_DBC_003 {
            get {
                return ResourceManager.GetString("UT_DBC_DBC_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データを削除しました。（データ情報：{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DBC_DBC_004 {
            get {
                return ResourceManager.GetString("UT_DBC_DBC_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DCM_DCM_001 {
            get {
                return ResourceManager.GetString("UT_DCM_DCM_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続状況の取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DCM_DCM_002 {
            get {
                return ResourceManager.GetString("UT_DCM_DCM_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム定義の取得に失敗しました。（device-sid: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DCM_DCM_003 {
            get {
                return ResourceManager.GetString("UT_DCM_DCM_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成不要。（device-sid: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DCM_DCM_004 {
            get {
                return ResourceManager.GetString("UT_DCM_DCM_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成に失敗しました。（device-sid: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DCM_DCM_005 {
            get {
                return ResourceManager.GetString("UT_DCM_DCM_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキュー登録に失敗しました。（device-sid: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DCM_DCM_006 {
            get {
                return ResourceManager.GetString("UT_DCM_DCM_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキューを登録しました。（device-sid: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DCM_DCM_007 {
            get {
                return ResourceManager.GetString("UT_DCM_DCM_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DCM_DCM_008 {
            get {
                return ResourceManager.GetString("UT_DCM_DCM_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DDP_DDP_001 {
            get {
                return ResourceManager.GetString("UT_DDP_DDP_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（message-id: {0}）（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DDP_DDP_002 {
            get {
                return ResourceManager.GetString("UT_DDP_DDP_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディスクドライブ予兆監視アラーム定義の取得に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DDP_DDP_003 {
            get {
                return ResourceManager.GetString("UT_DDP_DDP_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解析結果の検索に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DDP_DDP_004 {
            get {
                return ResourceManager.GetString("UT_DDP_DDP_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解析結果の保存に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DDP_DDP_005 {
            get {
                return ResourceManager.GetString("UT_DDP_DDP_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成不要。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DDP_DDP_006 {
            get {
                return ResourceManager.GetString("UT_DDP_DDP_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DDP_DDP_007 {
            get {
                return ResourceManager.GetString("UT_DDP_DDP_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキュー登録に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DDP_DDP_008 {
            get {
                return ResourceManager.GetString("UT_DDP_DDP_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキューを登録しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DDP_DDP_009 {
            get {
                return ResourceManager.GetString("UT_DDP_DDP_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再送用メッセージの保存に失敗しました。（message-id: {0}）（message: {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DDP_DDP_010 {
            get {
                return ResourceManager.GetString("UT_DDP_DDP_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DDP_DDP_011 {
            get {
                return ResourceManager.GetString("UT_DDP_DDP_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DUM_DUM_001 {
            get {
                return ResourceManager.GetString("UT_DUM_DUM_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（{1}）（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DUM_DUM_002 {
            get {
                return ResourceManager.GetString("UT_DUM_DUM_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディレクトリ通信監視アラーム定義の取得に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DUM_DUM_003 {
            get {
                return ResourceManager.GetString("UT_DUM_DUM_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成不要。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DUM_DUM_004 {
            get {
                return ResourceManager.GetString("UT_DUM_DUM_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DUM_DUM_005 {
            get {
                return ResourceManager.GetString("UT_DUM_DUM_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキュー登録に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DUM_DUM_006 {
            get {
                return ResourceManager.GetString("UT_DUM_DUM_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキューを登録しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DUM_DUM_007 {
            get {
                return ResourceManager.GetString("UT_DUM_DUM_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再送用メッセージの保存に失敗しました。（message-id: {0}）（message: {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DUM_DUM_008 {
            get {
                return ResourceManager.GetString("UT_DUM_DUM_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_DUM_DUM_009 {
            get {
                return ResourceManager.GetString("UT_DUM_DUM_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLM_FLM_001 {
            get {
                return ResourceManager.GetString("UT_FLM_FLM_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（message-id: {0}）（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLM_FLM_002 {
            get {
                return ResourceManager.GetString("UT_FLM_FLM_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   故障発生監視アラーム定義の取得に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLM_FLM_003 {
            get {
                return ResourceManager.GetString("UT_FLM_FLM_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成不要。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLM_FLM_004 {
            get {
                return ResourceManager.GetString("UT_FLM_FLM_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLM_FLM_005 {
            get {
                return ResourceManager.GetString("UT_FLM_FLM_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキュー登録に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLM_FLM_006 {
            get {
                return ResourceManager.GetString("UT_FLM_FLM_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキューを登録しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLM_FLM_007 {
            get {
                return ResourceManager.GetString("UT_FLM_FLM_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再送用メッセージの保存に失敗しました。（message-id: {0}）（message: {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLM_FLM_008 {
            get {
                return ResourceManager.GetString("UT_FLM_FLM_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLM_FLM_009 {
            get {
                return ResourceManager.GetString("UT_FLM_FLM_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLP_FLP_001 {
            get {
                return ResourceManager.GetString("UT_FLP_FLP_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（message-id: {0}）（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLP_FLP_002 {
            get {
                return ResourceManager.GetString("UT_FLP_FLP_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   故障予兆監視アラーム定義の取得に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLP_FLP_003 {
            get {
                return ResourceManager.GetString("UT_FLP_FLP_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成不要。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLP_FLP_004 {
            get {
                return ResourceManager.GetString("UT_FLP_FLP_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLP_FLP_005 {
            get {
                return ResourceManager.GetString("UT_FLP_FLP_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキュー登録に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLP_FLP_006 {
            get {
                return ResourceManager.GetString("UT_FLP_FLP_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキューを登録しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLP_FLP_007 {
            get {
                return ResourceManager.GetString("UT_FLP_FLP_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再送用メッセージの保存に失敗しました。（message-id: {0}）（message: {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLP_FLP_008 {
            get {
                return ResourceManager.GetString("UT_FLP_FLP_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_FLP_FLP_009 {
            get {
                return ResourceManager.GetString("UT_FLP_FLP_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_INM_INM_001 {
            get {
                return ResourceManager.GetString("UT_INM_INM_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（message-id: {0}）（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_INM_INM_002 {
            get {
                return ResourceManager.GetString("UT_INM_INM_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストール監視アラーム定義の取得に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_INM_INM_003 {
            get {
                return ResourceManager.GetString("UT_INM_INM_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成不要。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_INM_INM_004 {
            get {
                return ResourceManager.GetString("UT_INM_INM_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_INM_INM_005 {
            get {
                return ResourceManager.GetString("UT_INM_INM_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキュー登録に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_INM_INM_006 {
            get {
                return ResourceManager.GetString("UT_INM_INM_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキューを登録しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_INM_INM_007 {
            get {
                return ResourceManager.GetString("UT_INM_INM_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再送用メッセージの保存に失敗しました。（message-id: {0}）（message: {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_INM_INM_008 {
            get {
                return ResourceManager.GetString("UT_INM_INM_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_INM_INM_009 {
            get {
                return ResourceManager.GetString("UT_INM_INM_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PBP_PBP_001 {
            get {
                return ResourceManager.GetString("UT_PBP_PBP_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（message-id: {0}）（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PBP_PBP_002 {
            get {
                return ResourceManager.GetString("UT_PBP_PBP_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パネル放電破壊予兆監視アラーム定義の取得に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PBP_PBP_003 {
            get {
                return ResourceManager.GetString("UT_PBP_PBP_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成不要。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PBP_PBP_004 {
            get {
                return ResourceManager.GetString("UT_PBP_PBP_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PBP_PBP_005 {
            get {
                return ResourceManager.GetString("UT_PBP_PBP_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキュー登録に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PBP_PBP_006 {
            get {
                return ResourceManager.GetString("UT_PBP_PBP_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキューを登録しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PBP_PBP_007 {
            get {
                return ResourceManager.GetString("UT_PBP_PBP_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再送用メッセージの保存に失敗しました。（message-id: {0}）（message: {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PBP_PBP_008 {
            get {
                return ResourceManager.GetString("UT_PBP_PBP_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PBP_PBP_009 {
            get {
                return ResourceManager.GetString("UT_PBP_PBP_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PCM_PCM_001 {
            get {
                return ResourceManager.GetString("UT_PCM_PCM_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続状況の取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PCM_PCM_002 {
            get {
                return ResourceManager.GetString("UT_PCM_PCM_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム定義の取得に失敗しました。（parent-child-connect-sid: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PCM_PCM_003 {
            get {
                return ResourceManager.GetString("UT_PCM_PCM_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成不要。（parent-child-connect-sid: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PCM_PCM_004 {
            get {
                return ResourceManager.GetString("UT_PCM_PCM_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成に失敗しました。（parent-child-connect-sid: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PCM_PCM_005 {
            get {
                return ResourceManager.GetString("UT_PCM_PCM_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキュー登録に失敗しました。（parent-child-connect-sid: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PCM_PCM_006 {
            get {
                return ResourceManager.GetString("UT_PCM_PCM_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキューを登録しました。（parent-child-connect-sid: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PCM_PCM_007 {
            get {
                return ResourceManager.GetString("UT_PCM_PCM_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PCM_PCM_008 {
            get {
                return ResourceManager.GetString("UT_PCM_PCM_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PDP_PDP_001 {
            get {
                return ResourceManager.GetString("UT_PDP_PDP_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（message-id: {0}）（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PDP_PDP_002 {
            get {
                return ResourceManager.GetString("UT_PDP_PDP_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パネル欠陥予兆監視アラーム定義の取得に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PDP_PDP_003 {
            get {
                return ResourceManager.GetString("UT_PDP_PDP_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成不要。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PDP_PDP_004 {
            get {
                return ResourceManager.GetString("UT_PDP_PDP_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PDP_PDP_005 {
            get {
                return ResourceManager.GetString("UT_PDP_PDP_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキュー登録に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PDP_PDP_006 {
            get {
                return ResourceManager.GetString("UT_PDP_PDP_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキューを登録しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PDP_PDP_007 {
            get {
                return ResourceManager.GetString("UT_PDP_PDP_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再送用メッセージの保存に失敗しました。（message-id: {0}）（message: {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PDP_PDP_008 {
            get {
                return ResourceManager.GetString("UT_PDP_PDP_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_PDP_PDP_009 {
            get {
                return ResourceManager.GetString("UT_PDP_PDP_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TCP_TCP_001 {
            get {
                return ResourceManager.GetString("UT_TCP_TCP_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（message-id: {0}）（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TCP_TCP_002 {
            get {
                return ResourceManager.GetString("UT_TCP_TCP_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管電流経時劣化予兆監視アラーム定義の取得に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TCP_TCP_003 {
            get {
                return ResourceManager.GetString("UT_TCP_TCP_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成不要。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TCP_TCP_004 {
            get {
                return ResourceManager.GetString("UT_TCP_TCP_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TCP_TCP_005 {
            get {
                return ResourceManager.GetString("UT_TCP_TCP_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキュー登録に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TCP_TCP_006 {
            get {
                return ResourceManager.GetString("UT_TCP_TCP_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキューを登録しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TCP_TCP_007 {
            get {
                return ResourceManager.GetString("UT_TCP_TCP_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再送用メッセージの保存に失敗しました。（message-id: {0}）（message: {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TCP_TCP_008 {
            get {
                return ResourceManager.GetString("UT_TCP_TCP_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TCP_TCP_009 {
            get {
                return ResourceManager.GetString("UT_TCP_TCP_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TDP_TDP_001 {
            get {
                return ResourceManager.GetString("UT_TDP_TDP_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（message-id: {0}）（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TDP_TDP_002 {
            get {
                return ResourceManager.GetString("UT_TDP_TDP_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管球劣化予兆監視アラーム定義の取得に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TDP_TDP_003 {
            get {
                return ResourceManager.GetString("UT_TDP_TDP_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成不要。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TDP_TDP_004 {
            get {
                return ResourceManager.GetString("UT_TDP_TDP_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TDP_TDP_005 {
            get {
                return ResourceManager.GetString("UT_TDP_TDP_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキュー登録に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TDP_TDP_006 {
            get {
                return ResourceManager.GetString("UT_TDP_TDP_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキューを登録しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TDP_TDP_007 {
            get {
                return ResourceManager.GetString("UT_TDP_TDP_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再送用メッセージの保存に失敗しました。（message-id: {0}）（message: {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TDP_TDP_008 {
            get {
                return ResourceManager.GetString("UT_TDP_TDP_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TDP_TDP_009 {
            get {
                return ResourceManager.GetString("UT_TDP_TDP_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TSM_TSM_001 {
            get {
                return ResourceManager.GetString("UT_TSM_TSM_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータが不正です。（message-id: {0}）（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TSM_TSM_002 {
            get {
                return ResourceManager.GetString("UT_TSM_TSM_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   温度センサ監視アラーム定義の取得に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TSM_TSM_003 {
            get {
                return ResourceManager.GetString("UT_TSM_TSM_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成不要。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TSM_TSM_004 {
            get {
                return ResourceManager.GetString("UT_TSM_TSM_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム生成に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TSM_TSM_005 {
            get {
                return ResourceManager.GetString("UT_TSM_TSM_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキュー登録に失敗しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TSM_TSM_006 {
            get {
                return ResourceManager.GetString("UT_TSM_TSM_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラームキューを登録しました。（message-id: {0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TSM_TSM_007 {
            get {
                return ResourceManager.GetString("UT_TSM_TSM_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再送用メッセージの保存に失敗しました。（message-id: {0}）（message: {1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TSM_TSM_008 {
            get {
                return ResourceManager.GetString("UT_TSM_TSM_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション設定が不正です。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UT_TSM_TSM_009 {
            get {
                return ResourceManager.GetString("UT_TSM_TSM_009", resourceCulture);
            }
        }
    }
}
