//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Core.Utility.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtDeliveryGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DtDeliveryGroup()
        {
            this.DtDeliveryResult = new HashSet<DtDeliveryResult>();
        }
        public long Sid { get; set; }
    
        public long DeliveryFileSid { get; set; }
    
        public long DeliveryGroupStatusSid { get; set; }
    
        public string Name { get; set; }
    
        public Nullable<System.DateTime> StartDatetime { get; set; }
    
        public Nullable<short> DownloadDelayTime { get; set; }
    
        public System.DateTime CreateDatetime { get; set; }
    
        public System.DateTime UpdateDatetime { get; set; }
    
        public byte[] RowVersion { get; set; }
    
        public virtual DtDeliveryFile DtDeliveryFile { get; set; }
    
        public virtual MtDeliveryGroupStatus MtDeliveryGroupStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtDeliveryResult> DtDeliveryResult { get; set; }
    
    }
}
