//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Core.Utility.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DtDevice()
        {
            this.DtDeliveryResult = new HashSet<DtDeliveryResult>();
            this.DtDeliveryResult1 = new HashSet<DtDeliveryResult>();
            this.DtDeviceFile = new HashSet<DtDeviceFile>();
            this.DtDirectoryUsage = new HashSet<DtDirectoryUsage>();
            this.DtDiskDrive = new HashSet<DtDiskDrive>();
            this.DtDrive = new HashSet<DtDrive>();
            this.DtDxaBillLog = new HashSet<DtDxaBillLog>();
            this.DtDxaQcLog = new HashSet<DtDxaQcLog>();
            this.DtEquipmentUsage = new HashSet<DtEquipmentUsage>();
            this.DtInstallResult = new HashSet<DtInstallResult>();
            this.DtInventory = new HashSet<DtInventory>();
            this.DtParentChildConnect = new HashSet<DtParentChildConnect>();
            this.DtParentChildConnect1 = new HashSet<DtParentChildConnect>();
            this.DtPlusServiceBillLog = new HashSet<DtPlusServiceBillLog>();
            this.DtSoftVersion = new HashSet<DtSoftVersion>();
        }
        public long Sid { get; set; }
    
        public Nullable<long> EquipmentModelSid { get; set; }
    
        public long InstallTypeSid { get; set; }
    
        public long ConnectStatusSid { get; set; }
    
        public System.Guid EdgeId { get; set; }
    
        public string EquipmentUid { get; set; }
    
        public string RemoteConnectUid { get; set; }
    
        public string RmsSoftVersion { get; set; }
    
        public Nullable<System.DateTime> ConnectStartDatetime { get; set; }
    
        public Nullable<System.DateTime> ConnectUpdateDatetime { get; set; }
    
        public System.DateTime CreateDatetime { get; set; }
    
        public System.DateTime UpdateDatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtDeliveryResult> DtDeliveryResult { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtDeliveryResult> DtDeliveryResult1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtDeviceFile> DtDeviceFile { get; set; }
    
        public virtual MtConnectStatus MtConnectStatus { get; set; }
    
        public virtual MtInstallType MtInstallType { get; set; }
    
        public virtual MtEquipmentModel MtEquipmentModel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtDirectoryUsage> DtDirectoryUsage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtDiskDrive> DtDiskDrive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtDrive> DtDrive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtDxaBillLog> DtDxaBillLog { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtDxaQcLog> DtDxaQcLog { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtEquipmentUsage> DtEquipmentUsage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtInstallResult> DtInstallResult { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtInventory> DtInventory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtParentChildConnect> DtParentChildConnect { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtParentChildConnect> DtParentChildConnect1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtPlusServiceBillLog> DtPlusServiceBillLog { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtSoftVersion> DtSoftVersion { get; set; }
    
    }
}
