//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Core.Utility.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtDeliveryFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DtDeliveryFile()
        {
            this.DtDeliveryGroup = new HashSet<DtDeliveryGroup>();
            this.DtDeliveryModel = new HashSet<DtDeliveryModel>();
        }
        public long Sid { get; set; }
    
        public long DeliveryFileTypeSid { get; set; }
    
        public Nullable<long> InstallTypeSid { get; set; }
    
        public string FilePath { get; set; }
    
        public string Version { get; set; }
    
        public string InstallableVersion { get; set; }
    
        public string Description { get; set; }
    
        public string InformationId { get; set; }
    
        public Nullable<bool> IsCanceled { get; set; }
    
        public System.DateTime CreateDatetime { get; set; }
    
        public System.DateTime UpdateDatetime { get; set; }
    
        public byte[] RowVersion { get; set; }
    
        public virtual MtDeliveryFileType MtDeliveryFileType { get; set; }
    
        public virtual MtInstallType MtInstallType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtDeliveryGroup> DtDeliveryGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtDeliveryModel> DtDeliveryModel { get; set; }
    
    }
}
