//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Core.Utility.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtDirectoryUsage
    {
        public long Sid { get; set; }
    
        public long DeviceSid { get; set; }
    
        public string SourceEquipmentUid { get; set; }
    
        public string DetailInfo { get; set; }
    
        public Nullable<System.DateTime> CollectDatetime { get; set; }
    
        public string MessageId { get; set; }
    
        public System.DateTime CreateDatetime { get; set; }
    
        public virtual DtDevice DtDevice { get; set; }
    
    }
}
