//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Core.Utility.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtInstallResult
    {
        public long Sid { get; set; }
    
        public long DeviceSid { get; set; }
    
        public Nullable<long> DeliveryResultSid { get; set; }
    
        public long InstallResultStatusSid { get; set; }
    
        public string SourceEquipmentUid { get; set; }
    
        public string ReleaseVersion { get; set; }
    
        public string BeforeVersion { get; set; }
    
        public string AfterVervion { get; set; }
    
        public Nullable<bool> IsSuccess { get; set; }
    
        public string ErrorCode { get; set; }
    
        public string ErrorDescription { get; set; }
    
        public Nullable<bool> IsAuto { get; set; }
    
        public string Method { get; set; }
    
        public string Process { get; set; }
    
        public Nullable<System.DateTime> UpdateStratDatetime { get; set; }
    
        public Nullable<System.DateTime> UpdateEndDatetime { get; set; }
    
        public string ComputerName { get; set; }
    
        public string IpAddress { get; set; }
    
        public string ServerClientKind { get; set; }
    
        public Nullable<bool> HasRepairReport { get; set; }
    
        public Nullable<System.DateTime> EventDatetime { get; set; }
    
        public Nullable<System.DateTime> CollectDatetime { get; set; }
    
        public string MessageId { get; set; }
    
        public System.DateTime CreateDatetime { get; set; }
    
        public virtual DtDeliveryResult DtDeliveryResult { get; set; }
    
        public virtual DtDevice DtDevice { get; set; }
    
        public virtual MtInstallResultStatus MtInstallResultStatus { get; set; }
    
    }
}
