//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Core.Utility.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtParentChildConnect
    {
        public long Sid { get; set; }
    
        public long ParentDeviceSid { get; set; }
    
        public long ChildDeviceSid { get; set; }
    
        public Nullable<bool> ParentResult { get; set; }
    
        public Nullable<System.DateTime> ParentConfirmDatetime { get; set; }
    
        public Nullable<System.DateTime> ParentLastConnectDatetime { get; set; }
    
        public Nullable<bool> ChildResult { get; set; }
    
        public Nullable<System.DateTime> ChildConfirmDatetime { get; set; }
    
        public Nullable<System.DateTime> ChildLastConnectDatetime { get; set; }
    
        public System.DateTime CreateDatetime { get; set; }
    
        public System.DateTime UpdateDatetime { get; set; }
    
        public virtual DtDevice DtDevice { get; set; }
    
        public virtual DtDevice DtDevice1 { get; set; }
    
    }
}
