//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Core.Utility.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtPlusServiceBillLog
    {
        public long Sid { get; set; }
    
        public long DeviceSid { get; set; }
    
        public string SourceEquipmentUid { get; set; }
    
        public string TypeName { get; set; }
    
        public Nullable<bool> BillFlg { get; set; }
    
        public string PatientId { get; set; }
    
        public Nullable<byte> Sex { get; set; }
    
        public Nullable<byte> Age { get; set; }
    
        public string StudyInstanceUid { get; set; }
    
        public string SopInstanceUid { get; set; }
    
        public Nullable<System.DateTime> StudyDatetime { get; set; }
    
        public Nullable<double> MeasureValue { get; set; }
    
        public Nullable<System.DateTime> MeasureDatetime { get; set; }
    
        public Nullable<System.DateTime> CollectDatetime { get; set; }
    
        public System.DateTime CreateDatetime { get; set; }
    
        public System.DateTime UpdateDatetime { get; set; }
    
        public virtual DtDevice DtDevice { get; set; }
    
    }
}
