//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Core.Utility.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtStorageConfig
    {
        public long Sid { get; set; }
    
        public string Name { get; set; }
    
        public string Url { get; set; }
    
        public string Sas { get; set; }
    
        public System.DateTime CreateDatetime { get; set; }
    
        public System.DateTime UpdateDatetime { get; set; }
    
    }
}
