//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rms.Server.Core.Utility.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class MtEquipmentModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MtEquipmentModel()
        {
            this.DtDeliveryModel = new HashSet<DtDeliveryModel>();
            this.DtDevice = new HashSet<DtDevice>();
            this.DtSoftVersion = new HashSet<DtSoftVersion>();
            this.MtSoftVersionConvert = new HashSet<MtSoftVersionConvert>();
        }
        public long Sid { get; set; }
    
        public long EquipmentTypeSid { get; set; }
    
        public string Code { get; set; }
    
        public string Description { get; set; }
    
        public System.DateTime CreateDatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtDeliveryModel> DtDeliveryModel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtDevice> DtDevice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DtSoftVersion> DtSoftVersion { get; set; }
    
        public virtual MtEquipmentType MtEquipmentType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MtSoftVersionConvert> MtSoftVersionConvert { get; set; }
    
    }
}
